<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>aaf917e6-e85f-4627-86cb-6a7edc2ac6d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.h5p-question-iv-continue.h5p-joubelui-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cd3d489-8f1a-45ea-99cd-577cb74112e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h5p-question-iv-continue h5p-joubelui-button</value>
      <webElementGuid>ddf292b1-b08e-4436-9116-291b431d8072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>169190aa-9e81-4f4b-b018-d9bef82906d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>f7e85ffa-20e3-4740-9dd0-bc8cd8d9c44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h5p-iframe&quot;]/body[1]/div[@class=&quot;h5p-content h5p-initialized h5p-frame using-mouse&quot;]/div[@class=&quot;h5p-container h5p-standalone h5p-interactive-video&quot;]/div[@class=&quot;h5p-video-wrapper h5p-video hardware-accelerated&quot;]/div[@class=&quot;h5p-overlay h5p-ie-transparent-background&quot;]/div[@class=&quot;h5p-interaction h5p-poster h5p-truefalse-interaction h5p-dragnbar-element&quot;]/div[@class=&quot;h5p-interaction-outer&quot;]/div[@class=&quot;h5p-interaction-inner h5p-frame h5p-question h5p-true-false&quot;]/div[@class=&quot;h5p-question-buttons h5p-question-visible has-scorebar wrap&quot;]/button[@class=&quot;h5p-question-iv-continue h5p-joubelui-button&quot;]</value>
      <webElementGuid>161c0c7e-2eab-4103-895e-e2ef07ddac1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Interactive activity in course/Page_Katalon Title/iframe_Restore_h5p-iframe-147</value>
      <webElementGuid>9ffd9f1d-b87a-4766-95dd-4bad9041013f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>890470ae-a73f-4aa4-954b-cf4e6e8834db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::button[1]</value>
      <webElementGuid>23981655-139b-44dc-b4d5-0c37df608b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You got 1 out of 1 points'])[1]/following::button[1]</value>
      <webElementGuid>b6af501e-0d72-4e82-a63f-c0cf13c78cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current time: 0 Minutes, 1 Seconds'])[1]/preceding::button[1]</value>
      <webElementGuid>53e48f87-bfc3-4c15-a988-5872974793df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current time: 0 Minutes, 1 Seconds'])[2]/preceding::button[1]</value>
      <webElementGuid>65d8f8f3-9d2e-4f46-8e4e-9598d60a667c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>d7a22ca2-d944-4e76-817d-5795d6b7ade3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>25b02993-ee49-4e9e-b1c0-f0455890a653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>1193bc7d-0292-49fa-98b7-06e3d39401d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
