<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check</name>
   <tag></tag>
   <elementGuidId>7d1fe935-dffe-4e40-ad54-ffa2d3e3bde7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.h5p-question-check-answer.h5p-joubelui-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f6923de-c6ae-46d4-a076-b18eebc523ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h5p-question-check-answer h5p-joubelui-button</value>
      <webElementGuid>0de55046-a0f5-40bb-9ed0-f81bec1ba4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Check the answers. The responses will be marked as correct, incorrect, or unanswered.</value>
      <webElementGuid>64ea513c-414f-4d0e-9500-14f32284db1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e66f34c-3520-442e-b5c8-c5b15f585014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check</value>
      <webElementGuid>6979b73e-6351-4971-ac03-6dfffbc6655b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h5p-iframe&quot;]/body[1]/div[@class=&quot;h5p-content h5p-initialized h5p-frame using-mouse&quot;]/div[@class=&quot;h5p-container h5p-standalone h5p-interactive-video&quot;]/div[@class=&quot;h5p-video-wrapper h5p-video hardware-accelerated&quot;]/div[@class=&quot;h5p-overlay h5p-ie-transparent-background&quot;]/div[@class=&quot;h5p-interaction h5p-poster h5p-truefalse-interaction h5p-dragnbar-element&quot;]/div[@class=&quot;h5p-interaction-outer&quot;]/div[@class=&quot;h5p-interaction-inner h5p-frame h5p-question h5p-true-false&quot;]/div[@class=&quot;h5p-question-buttons h5p-question-visible&quot;]/button[@class=&quot;h5p-question-check-answer h5p-joubelui-button&quot;]</value>
      <webElementGuid>358f3f0e-13a6-47bb-9da0-dfb15b519e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Interactive activity in course/Page_Katalon Title/iframe_Restore_h5p-iframe-147</value>
      <webElementGuid>e02b14a8-fb2a-47c5-88e3-a55c247d8e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>48efd5ce-735e-45ad-ad96-981c75ac4bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='False'])[1]/following::button[1]</value>
      <webElementGuid>6bdc0179-763d-4546-afe3-b43be72c51b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='True'])[1]/following::button[1]</value>
      <webElementGuid>b20c524a-94a2-49b4-b327-e7240078ad4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current time: 0 Minutes, 1 Seconds'])[1]/preceding::button[1]</value>
      <webElementGuid>659b798d-cfb2-4f96-957a-9f51f3e41ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current time: 0 Minutes, 1 Seconds'])[2]/preceding::button[1]</value>
      <webElementGuid>c5cb1f1a-9439-4f70-ad7c-af91ba2b0e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check']/parent::*</value>
      <webElementGuid>f117608b-4da1-45ea-aa30-cfca507bfff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5104f636-4627-469e-9453-c3e3e50d2714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Check' or . = 'Check')]</value>
      <webElementGuid>6079e3b9-9057-47a0-b960-1e629107f588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
