<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Edit_men men-close-circle-outline</name>
   <tag></tag>
   <elementGuidId>1674de26-057b-4682-b2a7-b1d80f6fb611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.men.men-close-circle-outline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='region-main']/div/div/div/div[2]/table/tbody/tr/td[4]/span/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7e4cf701-a3d1-4aae-a329-6f27cdc94da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>men men-close-circle-outline</value>
      <webElementGuid>0fb46b90-9f9f-45a8-aed1-d1a6b136d21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0bf342fa-42a3-42c5-90bf-db74b1f2f988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region-main&quot;)/div[@class=&quot;card card-block content-shadow not-card&quot;]/div[1]/div[@class=&quot;content-title&quot;]/div[@class=&quot;plms-learningpaths p-4&quot;]/table[@class=&quot;table generaltable row col-xs-12 col-sm-12 title_lp_index&quot;]/tbody[1]/tr[@class=&quot;plms-learningpath mar-btm&quot;]/td[@class=&quot;learningpaths-actions&quot;]/span[@class=&quot;action-box&quot;]/a[@class=&quot;delete-learning-path deletelp&quot;]/i[@class=&quot;men men-close-circle-outline&quot;]</value>
      <webElementGuid>20baae9b-636e-4ebb-b86e-19f7d4ff5793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='region-main']/div/div/div/div[2]/table/tbody/tr/td[4]/span/a[2]/i</value>
      <webElementGuid>132ac349-4a5c-4618-ba75-86a730e617a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a[2]/i</value>
      <webElementGuid>266d9dc8-4061-47ee-9f08-3dd581ce8228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
