<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Time_timelimitnumber</name>
   <tag></tag>
   <elementGuidId>5004a252-ce6d-4380-941f-17b4be247f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_timelimit_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_timelimit_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>152b5c27-b2a0-43e3-bb61-eabd55cfdad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c3080bf-769c-4ccb-b204-2652b8300166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>3a87297e-ab79-4f46-b522-980a1832d24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timelimit[number]</value>
      <webElementGuid>5dc7b165-961d-4461-880e-19fb851c22fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_timelimit_number</value>
      <webElementGuid>d1217264-c150-4803-a05f-46d07a1ce106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2a2a07e-9b58-4e5a-a62c-126f70082d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>02bf288d-7ff3-4a5f-839a-e2e09d4a987a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_timelimit_number&quot;)</value>
      <webElementGuid>22b75033-5ce4-4de9-a061-693144b81399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_timelimit_number']</value>
      <webElementGuid>787f90ff-23f5-4a21-b911-a6961369c771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1742283838030_3086']/input</value>
      <webElementGuid>6f7afabc-99e0-46ba-ba6c-c1f71c5d197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>d3dab6e5-37c9-450d-90de-f93dd82cffc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'timelimit[number]' and @id = 'id_timelimit_number']</value>
      <webElementGuid>7ce48277-e892-4090-aada-2f30a647cf56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
