<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Require View_completionview</name>
   <tag></tag>
   <elementGuidId>9e124fa8-5ae1-41fe-b95b-f909cc60b266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_completionview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_completionview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10440581-d197-47f3-839b-4b9ac2e9323d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f8c36b98-b766-40e3-a5f3-f6bf02c8fae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>completionview</value>
      <webElementGuid>5ebc0c4d-8e39-4c24-9878-7dea4609bc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>95261def-6a69-4d1d-94cb-641803d3415e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_completionview</value>
      <webElementGuid>ab91ced2-a775-49fc-bc8f-0cf35b4779d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_completionview&quot;)</value>
      <webElementGuid>18e5ac04-6fb2-45c3-aedf-9847e8d667f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_completionview']</value>
      <webElementGuid>5b88a43c-4574-4417-a799-9adbf6ab0827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742283838030_3186']/input</value>
      <webElementGuid>dddf19f7-ec9c-47a3-bf20-51dfc593dc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[14]/div/div[2]/div[2]/input</value>
      <webElementGuid>4b9e90a4-62a0-43e5-9d57-fa8ccb6db4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'completionview' and @id = 'id_completionview']</value>
      <webElementGuid>599c3941-7596-40f7-92cf-884c9d5a6bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
