<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit Settings</name>
   <tag></tag>
   <elementGuidId>d5ddb96c-0b79-4b9a-bb8e-9f6ed65f7350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='actionmenuaction-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionmenuaction-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f930b86-6aab-402b-b425-2a02f80e11a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-action-text</value>
      <webElementGuid>be3d3a3f-857c-4bff-9da7-c9cda4fcfa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionmenuaction-14</value>
      <webElementGuid>b4364e11-3c0c-44eb-8e1e-2489616dc4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Settings</value>
      <webElementGuid>c838a05e-06d9-439a-a79a-0261fcf0746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionmenuaction-14&quot;)</value>
      <webElementGuid>cd76a731-7795-4092-adf1-ea4178a29c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionmenuaction-14']</value>
      <webElementGuid>18b00206-2a9f-4831-9d2a-b9d57429f072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1741247777348_593']/span</value>
      <webElementGuid>31b541bb-e543-4cd2-9279-91d07ea3db70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Topic'])[1]/following::span[4]</value>
      <webElementGuid>a933650c-c14a-461e-b477-cb4227a50576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Topic'])[1]/following::span[5]</value>
      <webElementGuid>c21007a5-f77c-423c-94a3-ecad97adc8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Right'])[2]/preceding::span[1]</value>
      <webElementGuid>b6dd3b22-e414-46af-9385-9c0ab0e71324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Left'])[2]/preceding::span[2]</value>
      <webElementGuid>9f26eb66-5505-4f3f-ad4e-620497eec24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/div/div[2]/span/div/div/div/div/a/span</value>
      <webElementGuid>f41b3658-bfcb-4767-a461-f8c5dc86da5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionmenuaction-14' and (text() = 'Edit Settings' or . = 'Edit Settings')]</value>
      <webElementGuid>3fbfb9c7-aef8-4ad8-89ac-66b858d25c85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
