<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Finish</name>
   <tag></tag>
   <elementGuidId>8aa28f0b-fff9-416b-8fa5-e044764ee90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#finish_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='finish_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b38e52d6-0b6d-44b4-9830-978e140b836a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>finish_btn</value>
      <webElementGuid>42a699ba-f121-4696-bb0f-8f5d600ac6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mt-button mr-4 new-btn-rnd</value>
      <webElementGuid>06a56ed2-e007-47ba-9fec-1262b3b36d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/blocks/configurable_reports/viewreport.php?id=840</value>
      <webElementGuid>926c28dd-5043-4787-bc3e-f09918dfe826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finish</value>
      <webElementGuid>ebb8987b-3156-4333-9027-55104fd1de85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;finish_btn&quot;)</value>
      <webElementGuid>e6b5ca3b-d78c-4a12-9198-a2ff64d28987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='finish_btn']</value>
      <webElementGuid>a9eb64a1-7ab0-43c6-bc53-6c3e37ac79b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plms-course-wizard1']/div[3]/div[2]/a</value>
      <webElementGuid>605c87cc-5d75-4182-bd8c-f8a31263268e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Finish')]</value>
      <webElementGuid>a60ec867-04f9-4ef7-80ec-9bd3fbc05400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Filter'])[1]/following::a[1]</value>
      <webElementGuid>5487bde6-2f4c-41f9-b3b3-1a646d170313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[2]</value>
      <webElementGuid>0d085036-f78c-4a4f-9b12-5d9f87f1692e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Side panel'])[1]/preceding::a[1]</value>
      <webElementGuid>f7f00016-70d8-49d6-bf2a-3f17c1b82baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[2]</value>
      <webElementGuid>a5803625-94ca-4b9c-a3c8-a9dd17b2a611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finish']/parent::*</value>
      <webElementGuid>2268f610-3fe1-44eb-8b7e-c16a45e5132f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/blocks/configurable_reports/viewreport.php?id=840')]</value>
      <webElementGuid>100c09b9-f5f7-49b8-969a-59b87daa6f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>395958aa-b44d-4f6b-b6c7-481373b2e02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'finish_btn' and @href = 'https://plms-php81.paradisolms.net/blocks/configurable_reports/viewreport.php?id=840' and (text() = 'Finish' or . = 'Finish')]</value>
      <webElementGuid>3878e165-fb6e-4333-b692-6695d4f870d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
