<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QA COURSE 2401</name>
   <tag></tag>
   <elementGuidId>150beac6-df61-462f-95db-1c5ce5094c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form_autocomplete_selection-1743567900984']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_autocomplete_selection-1743567900984</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93337d57-e1d0-489a-8496-d85defc43c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-autocomplete-selection w-100 form-autocomplete-multiple</value>
      <webElementGuid>fb227f36-7b35-48ab-b7e2-e4e1c33deb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_autocomplete_selection-1743567900984</value>
      <webElementGuid>64fa6997-2c02-4108-99bb-2d5cfb0bfdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c3b8adb6-40eb-44b4-b55b-86a3bc10e6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4965867-7d79-4d8c-ba3b-21a08bf3d7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>427329aa-0cd4-4fd3-aa66-ee82dc43220b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9153e06-f126-4248-be9a-3c24f2a2bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>form_autocomplete_selection-1743567900984-0</value>
      <webElementGuid>963e9a8b-343e-4d73-864e-4f701eb66a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        × QA COURSE 2401
    </value>
      <webElementGuid>0ccdf2c1-5604-4284-8c32-22e84845dda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_autocomplete_selection-1743567900984&quot;)</value>
      <webElementGuid>9f9163c8-3634-42c5-a2b4-963be1efd51b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='form_autocomplete_selection-1743567900984']</value>
      <webElementGuid>bfae60f6-9813-4c5c-8126-c31297a7bcd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1743567900483_52']/div[2]</value>
      <webElementGuid>d482f6c4-6eb6-42b3-a0e5-7990e5990167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add courses'])[1]/following::div[5]</value>
      <webElementGuid>55678899-dcb9-47b7-8a23-6e64a254347e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploaded Successfully'])[1]/following::div[15]</value>
      <webElementGuid>7cab0dbb-c4c4-4808-ba3d-b6f087e1645f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tenant course 201'])[2]/preceding::div[2]</value>
      <webElementGuid>c356ac4a-58f1-476c-b667-7648cc81057e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>8bffc038-c43c-47af-a8b7-7feff00d4b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'form_autocomplete_selection-1743567900984' and (text() = '
        × QA COURSE 2401
    ' or . = '
        × QA COURSE 2401
    ')]</value>
      <webElementGuid>4513abf3-1494-4de9-9ff4-f8fbe684664d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
