<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>a81958b1-7aa8-4ad5-98ba-951e0a113288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reports-columns-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reports-columns-add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0758e32-c242-4d76-bb37-bd998d257cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reports-columns-add</value>
      <webElementGuid>7e8a0329-be33-4691-a308-bfede949a78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-primary new-btn-rnd btn-report-editp</value>
      <webElementGuid>0e010e33-6d08-4e86-bade-2ced0b11ef5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add </value>
      <webElementGuid>efa038af-3f6d-47f5-a373-f92d4c3936f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reports-columns-add&quot;)</value>
      <webElementGuid>06a7cba8-b372-4a6f-b2f0-d0932d8fe936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reports-columns-add']</value>
      <webElementGuid>21ef827b-b065-4822-9fe2-8eeb66b347a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741272211211_65']/button</value>
      <webElementGuid>1142130c-76f1-465f-8d35-4eefaa5c2a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[[help_learningpath_required_courses]]'])[1]/following::button[1]</value>
      <webElementGuid>33b02b83-c66e-4f65-93a8-70d01b131eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[[help_learningpath_total_cohorts]]'])[1]/following::button[1]</value>
      <webElementGuid>564fa96f-6e9b-4ab7-a6b8-446c139e00c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>d84a2a95-da3e-4579-b801-36d311c0a371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Columns currently in the report'])[2]/preceding::button[2]</value>
      <webElementGuid>5dcc7d81-d125-4cbd-9acc-7dafa3482858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>89c23410-de74-422d-8cdd-3429a299746e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/button</value>
      <webElementGuid>214f55ad-9d1a-4eee-b891-bb4373276fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reports-columns-add' and (text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>c6a90dfe-7e7c-422d-abed-fedae10f81f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
