<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>a2b4b498-c85a-4d7c-9e76-c0a1017de8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columns_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='columns_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d55b0e1d-f474-4bdc-8550-f9696f359d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-round</value>
      <webElementGuid>9c90746f-d48c-4aa0-be05-878ee2fb2eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitbutton</value>
      <webElementGuid>de8d3ab9-f946-48e1-82aa-3d98860ca698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columns_button</value>
      <webElementGuid>4392e655-d2d1-43b5-b344-c60bac7e23ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44ffbe25-ecd4-4a6c-a5ad-7c1d0c49ad1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Save
            </value>
      <webElementGuid>6e975413-d98d-441a-b0a1-58633452b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741272251402_70&quot;)/button[@id=&quot;columns_button&quot;]</value>
      <webElementGuid>7fc439af-1800-4b80-850f-579ce738b66c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='columns_button']</value>
      <webElementGuid>4ae8af32-49b6-4e68-88ae-b089d3051564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1741272251402_70']/button</value>
      <webElementGuid>7080ba8a-7a77-4f79-895f-6362f6e6b42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail address of the user'])[1]/following::button[1]</value>
      <webElementGuid>740082d2-b81e-4ad8-a18d-e63f69de0842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Columns currently in the report'])[2]/following::button[1]</value>
      <webElementGuid>3ab0f195-ca00-4bb9-851a-d43d6f410bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Side panel'])[1]/preceding::button[1]</value>
      <webElementGuid>f1ed7cde-5f1b-42a3-a867-6a0a319f643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[2]</value>
      <webElementGuid>6eed491a-0b75-40b8-be1d-4cd6a0645bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>d2121016-6d79-4cef-8b98-5f15cb05af7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>2bdcedf4-1b8b-47e3-8a3f-fc4fcc82c921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'submitbutton' and @id = 'columns_button' and @type = 'button' and (text() = '
                Save
            ' or . = '
                Save
            ')]</value>
      <webElementGuid>1803b7a9-f4de-49f1-964a-d98f1f29da90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
