<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Email</name>
   <tag></tag>
   <elementGuidId>6903733f-02b9-469a-93b7-e0f5fcab8718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p[title=&quot;Email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='email']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0085165e-5417-4f95-a73b-06312c5dc1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>b23b7c43-f5e1-4709-877d-481f6ad3da4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>21b5a06e-de53-4d38-a98d-fb883e1615ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email&quot;)/div[@class=&quot;values pl-2 pr-2&quot;]/p[1]</value>
      <webElementGuid>9b4b14ef-b702-4b6f-950d-b293a915b88b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='email']/div/p</value>
      <webElementGuid>e71180de-3cf3-40c8-ae44-51ef658f10fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail address of the user'])[1]/following::p[1]</value>
      <webElementGuid>cb817127-0170-4f99-a8f0-d2b96dab0c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[2]/following::p[1]</value>
      <webElementGuid>d626311d-84a5-4923-ac6b-f39361404fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This column displays the user status (Active / Inactive)'])[1]/preceding::p[1]</value>
      <webElementGuid>bfc7caf9-4696-49cc-a55b-7c6c3521efde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email']/parent::*</value>
      <webElementGuid>53804903-4db9-4d4e-acc3-7478d8858382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/p</value>
      <webElementGuid>4e4b0f6c-698d-4fa8-89d5-31fcd7dd01a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Email' and (text() = 'Email' or . = 'Email')]</value>
      <webElementGuid>205be8f2-3494-4f85-9b13-178d5ba15c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
