<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Grades overview_dropdownMenuButton</name>
   <tag></tag>
   <elementGuidId>b1cff585-0f08-47d9-a004-80eb872f299c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d76c2668-88b6-4d80-80e6-33100545a066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-course dropdown-toggle</value>
      <webElementGuid>aa8edea7-1768-4801-9119-83f73b6533fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1397dde6-58ff-49d7-9ae4-cdbcc5632d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton</value>
      <webElementGuid>8e5f4e65-8c79-4ddd-8919-17b53a0a7e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>c4b1cc4a-24b0-41c9-bde0-a966646c4b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07831d96-2a23-4f3e-8be5-30f3429a636c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4383941d-c9a3-4199-b333-3b2752eff1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuButton&quot;)</value>
      <webElementGuid>9492aef9-63db-4a5b-9492-08820bfa8870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenuButton']</value>
      <webElementGuid>f5bbdd97-a8c3-4905-a91d-2c41d3eaf817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='lastTab']/div/button</value>
      <webElementGuid>00a0e999-4ab5-4ff7-a4fc-46cc1674f135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grades overview'])[1]/following::button[1]</value>
      <webElementGuid>0f3c4b3a-72a9-4e6e-b506-311ac22e75a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[1]/following::button[1]</value>
      <webElementGuid>dcf0e764-7b4b-40ed-b602-1ebfd3f18ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Badges'])[1]/preceding::button[1]</value>
      <webElementGuid>45839259-a3d2-4890-af13-a51690a65d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Competencies'])[1]/preceding::button[1]</value>
      <webElementGuid>fbca5c7a-4b99-4e2d-a79c-79e4aef33d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>33cfefec-3765-4fd2-b2d2-4965357e91c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownMenuButton']</value>
      <webElementGuid>ac5f96e4-4bcd-4bbc-a366-dafbfd40749c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
