<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Match the search text anywhere in the_df68c1</name>
   <tag></tag>
   <elementGuidId>618f688d-dedc-43bf-b34c-e61cbba94254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;award&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='award']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6cfc884-66e5-4f63-8f99-8424c4c8e24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f4659b52-d4cf-4271-83fe-d363095f5752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>award</value>
      <webElementGuid>6d2362fd-a6df-4cb6-9a80-88fb4cdc2abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>◄ Award badge</value>
      <webElementGuid>c1dfd800-5aef-4b6b-a053-453ec99194b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionbutton btn btn-secondary</value>
      <webElementGuid>118263ad-f00e-4f78-a41e-558234ee0622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741683856769_87&quot;)/td[@class=&quot;actions cell c1&quot;]/div[1]/input[@class=&quot;actionbutton btn btn-secondary&quot;]</value>
      <webElementGuid>adaa91ae-803f-4c97-a459-ee4a17526699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='award']</value>
      <webElementGuid>73d9b366-f9c2-4a61-b25c-7c5cebfe82fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='yui_3_17_2_1_1741683856769_87']/td[2]/div/input</value>
      <webElementGuid>08021747-dd75-4023-b764-3b0523f9d327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>4008cadd-3390-4beb-b37c-23dd98e80866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'award']</value>
      <webElementGuid>a4fdb7c7-7d3c-40cc-825d-166baaa2ee67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
