<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(ja)_keepmeloggedin</name>
   <tag></tag>
   <elementGuidId>750b2094-488e-43a7-8cdf-1ce441c0dce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keepmeloggedin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keepmeloggedin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db1529be-1713-4a5f-acd9-a27c0a566bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>10dc5107-95f1-496e-b5bd-3448198501ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keepmeloggedin</value>
      <webElementGuid>81203c94-2da9-4768-9394-e07c21a6e359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keepmeloggedin</value>
      <webElementGuid>b8740ea1-b01d-4561-8f3d-68c507c0e971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7f73413b-1657-4640-9bba-562778101bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keepmeloggedin&quot;)</value>
      <webElementGuid>6d32f8ad-46b7-4b7e-a63b-cf89253d5dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keepmeloggedin']</value>
      <webElementGuid>a459b7b7-580f-4fe8-b0fc-255b45af85ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div[4]/input</value>
      <webElementGuid>35e9d171-445a-4689-9ffc-886c1c97beb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b3616c01-270c-40f9-b813-db342ae97230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'keepmeloggedin' and @id = 'keepmeloggedin']</value>
      <webElementGuid>9cbb7d26-9510-41a1-be5c-76ff7638ac50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
