<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enrolment Methods</name>
   <tag></tag>
   <elementGuidId>897d47b1-0311-4c42-9aa5-51f4afd948d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='teacherdashslider']/div/div/div/div[2]/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1eff35b5-b800-49e1-8faf-01804af07b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/enrol/instances.php?id=1159</value>
      <webElementGuid>f21aa611-a76d-4d5b-9130-b5ce561781bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>0e587203-8edd-4815-8ac7-5f83eac3263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enrolment Methods</value>
      <webElementGuid>07fc0c0b-8d0b-4098-8b9b-e8776180c123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teacherdashslider&quot;)/div[@class=&quot;teacherdashboard&quot;]/div[@class=&quot;container-fluid pr-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;border-group userlinks&quot;]/div[@class=&quot;list-group&quot;]/a[@class=&quot;list-group-item&quot;]</value>
      <webElementGuid>6e4aea5b-daa2-4ceb-af80-ac81877a3476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='teacherdashslider']/div/div/div/div[2]/div/div[2]/a[3]</value>
      <webElementGuid>0d8a8d3c-e74f-4433-aa2b-d59ba41fd58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enrolment Methods')]</value>
      <webElementGuid>6fb8f624-064b-4adf-a3be-75a7619db982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[1]/following::a[1]</value>
      <webElementGuid>7246d7cb-44d5-413c-8a1d-1e796ed1800e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course participants'])[1]/following::a[2]</value>
      <webElementGuid>95cfbbdb-043f-4453-a4d8-1299a591c7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published as LTI tools'])[1]/preceding::a[1]</value>
      <webElementGuid>7cbce48b-d2f7-4d34-8bf4-398b30dcaf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Users'])[1]/preceding::a[2]</value>
      <webElementGuid>aa399027-3b76-4ee7-8023-c9292c24c8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enrolment Methods']/parent::*</value>
      <webElementGuid>29115372-ad97-4ccf-9367-26e4772b4a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/enrol/instances.php?id=1159')]</value>
      <webElementGuid>5f29ca67-890f-4a53-9ff7-04494f7bbb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a[3]</value>
      <webElementGuid>8306c9b1-5eed-4b35-97f7-30a37bf69d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/enrol/instances.php?id=1159' and (text() = 'Enrolment Methods' or . = 'Enrolment Methods')]</value>
      <webElementGuid>87645b28-58da-4c3f-be1d-e017f62f657e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
