<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Preview_men men-menu-dots</name>
   <tag></tag>
   <elementGuidId>ba3dccc1-6d1f-4899-919f-dfd46c3c58c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.men.men-menu-dots</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_teacherdash']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ea38c3e4-1920-4039-ba40-956e50df5172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>men men-menu-dots</value>
      <webElementGuid>4c310446-4bac-4d2d-8c84-1faefe81f7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e33db0b-35fd-4311-a205-dfbac2ab2e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_teacherdash&quot;)/i[@class=&quot;men men-menu-dots&quot;]</value>
      <webElementGuid>113958a0-d703-4c4a-91fd-4978ad5d0a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn_teacherdash']/i</value>
      <webElementGuid>7ea3e80a-f7fb-4649-9eb1-5861190ad34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>461bb635-9fef-435e-84b5-c537e57ff49f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
