<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete_1</name>
   <tag></tag>
   <elementGuidId>fa73c50c-3ca8-44bf-bc3a-2a66f2d1c3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='yui_3_17_2_1_1741071899241_861']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741071899241_861</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ebd486c-a987-4142-a623-e21cd61d60a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/course/mod.php?sesskey=6z2D8X9psC&amp;sr=0&amp;delete=9439</value>
      <webElementGuid>1602a01c-c73b-4f1d-b9a8-b9caba0acb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item editing_delete menu-action</value>
      <webElementGuid>86b8686f-eb3d-4c23-ac20-69c5114feaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>959448ef-140b-4de5-86b7-5302f578b479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sectionreturn</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4ac73d7-6d01-4a88-968b-4ee1bf00eac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>dc5b19d7-7234-4cbc-a899-f3ec301837f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>actionmenuaction-28</value>
      <webElementGuid>d7a3061e-133f-4c92-a484-201a1da70e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741071899241_861</value>
      <webElementGuid>116e74b9-a3ff-47b9-af94-87fb0fd3a0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            Delete
    </value>
      <webElementGuid>9aa2141f-3129-4e68-b3bb-59c2cd9ec4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741071899241_861&quot;)</value>
      <webElementGuid>8ec1bce2-7d31-4176-afa8-0b745cf2cf01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1741071899241_861']</value>
      <webElementGuid>fde00585-f47a-403a-be25-9b17e41974ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-menu-5-menu']/a[7]</value>
      <webElementGuid>ab7d6860-d02a-4ba4-9fac-0df70102a619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Roles'])[2]/following::a[1]</value>
      <webElementGuid>7501795f-5ffe-4617-a693-569163de97e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate'])[3]/following::a[2]</value>
      <webElementGuid>148ccca1-7e4e-46dc-b833-fc8f6fb8c871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file(s) here'])[2]/preceding::a[1]</value>
      <webElementGuid>0a3365bf-ac48-455c-adb3-8700c07fec0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=6z2D8X9psC&amp;sr=0&amp;delete=9439')]</value>
      <webElementGuid>88903987-b229-4653-a7cf-f7210a341079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/div/div[2]/span/div/div/div/div/a[7]</value>
      <webElementGuid>d0b923c9-0b23-4fed-94ce-eab30d2fd094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=6z2D8X9psC&amp;sr=0&amp;delete=9439' and @id = 'yui_3_17_2_1_1741071899241_861' and (text() = '
            
            Delete
    ' or . = '
            
            Delete
    ')]</value>
      <webElementGuid>6b551a02-1e61-495d-b115-f84497f56e7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
