<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Katalon File Upload Test update (Copy)</name>
   <tag></tag>
   <elementGuidId>be7ad92b-87fa-422a-a563-a08b37014b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='yui_3_17_2_1_1741071849053_852']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741071849053_852</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b2944c73-902e-4d72-b21c-5f36c5ca0219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Katalon File Upload Test update (Copy)</value>
      <webElementGuid>961dd317-2ca1-430f-8766-6ae5a959f9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741071849053_852</value>
      <webElementGuid>416f8a66-8195-4bd4-b033-2c100bf9838e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon File Upload Test update (Copy)</value>
      <webElementGuid>3ab445d4-9046-43f6-a1d3-98c6cc7fab2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741071849053_852&quot;)</value>
      <webElementGuid>e3cdf676-9f13-4136-a690-9ab46f9c3967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='yui_3_17_2_1_1741071849053_852']</value>
      <webElementGuid>70e3b8e6-0034-4dea-90e4-ea2ccad2db22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1741071849053_853']/p</value>
      <webElementGuid>641f6d65-a7d4-4f28-bce0-be9eac6c64aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The system marks this item complete according to conditions: Katalon File Upload Test update'])[1]/following::p[1]</value>
      <webElementGuid>5783a034-08e3-4a85-9d45-537b7146f85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/following::p[1]</value>
      <webElementGuid>e4fcb72b-88b9-4240-9940-2debd8b6e4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Settings'])[3]/preceding::p[1]</value>
      <webElementGuid>1014d973-9a97-47ec-8fb1-1034084ec3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Right'])[3]/preceding::p[1]</value>
      <webElementGuid>6dd7f567-d19d-4c94-9879-cc957805304c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon File Upload Test update (Copy)']/parent::*</value>
      <webElementGuid>05e7c71b-e86d-4d55-a189-97f5d0935b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/div/a/span/p</value>
      <webElementGuid>1f580678-5cd8-472b-8e81-73c84070d8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Katalon File Upload Test update (Copy)' and @id = 'yui_3_17_2_1_1741071849053_852' and (text() = 'Katalon File Upload Test update (Copy)' or . = 'Katalon File Upload Test update (Copy)')]</value>
      <webElementGuid>cd5f76ed-6b3c-4730-86d9-7686a2e2f0bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
