<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Delete Topic_Ellipse_454</name>
   <tag></tag>
   <elementGuidId>3c89799f-e243-41af-a68e-14f48b02cd43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#Ellipse_453</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action-menu-toggle-4 > #menu-dots-vertical_1_ > #Ellipse_454</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>4a93058c-9a56-4d61-b914-0735353bbb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Ellipse_454</value>
      <webElementGuid>219692a4-541d-4676-8add-71b636d473dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Ellipse 454</value>
      <webElementGuid>b0b5cd85-1858-48f2-ac75-ef4cca0273e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>57a302e7-4dee-4dd0-b52d-92c1118103c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ae1c1039-3f42-4675-897f-e30147f1c5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0c3b7d11-0ab3-4b7e-8fdd-97a8ce093f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(0 8)</value>
      <webElementGuid>e9545540-c838-4f41-a763-950ec8e281b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#334155</value>
      <webElementGuid>546b536d-255e-4860-8fc9-c6c484ba92c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-menu-toggle-4&quot;)/svg[@id=&quot;menu-dots-vertical_1_&quot;]/circle[@id=&quot;Ellipse_454&quot;]</value>
      <webElementGuid>c19eeecd-e4c4-45d0-8e46-78208ce6dc88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//circle[@id = 'Ellipse_454']</value>
      <webElementGuid>87ccf4fb-84b2-4b6b-ac4f-8c63e598d829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
