<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_gpt-3.5-turbo            gpt-3.5-tur_5e8193</name>
   <tag></tag>
   <elementGuidId>6c1f7b7a-fc7e-4636-866c-5b2a375c561e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_s_block_ai_quiz_generator_model</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_s_block_ai_quiz_generator_model']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d3532cb3-3fc3-4ad1-8c5d-e8dff78a53f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_s_block_ai_quiz_generator_model</value>
      <webElementGuid>15ac6767-e514-4ec5-adcf-7fc558335346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s_block_ai_quiz_generator_model</value>
      <webElementGuid>60208937-08fe-420a-9352-5017a8eb9623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1d5bde2-b06a-4d44-99fb-4ca713ff5d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            gpt-3.5-turbo
            gpt-3.5-turbo-16k
            gpt-4
            gpt-4-turbo
            gpt-4o
            gpt-4-32k
            gpt-4-1106-preview
    </value>
      <webElementGuid>23fd18d4-8535-4908-a3f4-fdf61da97cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_s_block_ai_quiz_generator_model&quot;)</value>
      <webElementGuid>d3f32450-0b5c-4f80-a37e-52804d8497bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_s_block_ai_quiz_generator_model']</value>
      <webElementGuid>7e8d180a-a078-4f64-baaa-76a1c4e0b9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1743756436866_64']/select</value>
      <webElementGuid>feb5ad9c-7fa4-439c-98d5-1507289b782c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='block_ai_quiz_generator | model'])[1]/following::select[1]</value>
      <webElementGuid>1aff8cd5-85c5-4318-9853-0e01daa44123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::select[1]</value>
      <webElementGuid>692cc604-1786-4efe-902b-6e8a1b238594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default: gpt-4'])[1]/preceding::select[1]</value>
      <webElementGuid>5cc87fb4-c5ce-4dd5-9bc6-08618d2b423c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promt'])[1]/preceding::select[1]</value>
      <webElementGuid>6ebaf9ef-c1d0-4fa0-aa3b-de1835fa5e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>31273025-9499-44db-9a98-aa2275332aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'id_s_block_ai_quiz_generator_model' and @name = 's_block_ai_quiz_generator_model' and (text() = '
            gpt-3.5-turbo
            gpt-3.5-turbo-16k
            gpt-4
            gpt-4-turbo
            gpt-4o
            gpt-4-32k
            gpt-4-1106-preview
    ' or . = '
            gpt-3.5-turbo
            gpt-3.5-turbo-16k
            gpt-4
            gpt-4-turbo
            gpt-4o
            gpt-4-32k
            gpt-4-1106-preview
    ')]</value>
      <webElementGuid>26f2f511-b544-46c8-a868-a187de024532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
