<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Categories</name>
   <tag></tag>
   <elementGuidId>8a731c89-c0b8-487d-a488-0a1d76f0fa6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='linkmaincontent']/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d00dbb29-9373-42b3-a888-de2d7712a569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>e526596c-11fa-4396-a8eb-c11966dcbb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/question/category.php?courseid=1159</value>
      <webElementGuid>4afc3239-6b0d-45ce-b06e-5c5ea27b1ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>80c67136-7bc2-499a-a934-0beb31bd7810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>ea1ad4c2-7bab-4f98-a8a9-ae813a3352e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkmaincontent&quot;)/div[1]/div[@class=&quot;questionbank-navigation&quot;]/ul[@class=&quot;nav nav-tabs mb-3&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>bd5d7d85-157f-4f8b-8eee-b56d77072070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkmaincontent']/div/div/ul/li[2]/a</value>
      <webElementGuid>38e0dec1-aeb9-4d5c-bde6-308fb8b4ea6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Categories')]</value>
      <webElementGuid>23355975-bab3-4a39-8b5a-db897c4e5fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/following::a[1]</value>
      <webElementGuid>c9cc89a3-49ce-49a3-81f3-2e071a93a1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No content added'])[1]/following::a[2]</value>
      <webElementGuid>2ee00315-da68-4cd1-a617-63ab43568e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/preceding::a[1]</value>
      <webElementGuid>e89b0100-c90b-438a-ad4f-1b82e903be77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::a[2]</value>
      <webElementGuid>0eba98e6-6777-48d5-b20d-47fa22985de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Categories']/parent::*</value>
      <webElementGuid>b7c6ef90-3651-4b8c-bfcf-42a98ca20e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/question/category.php?courseid=1159')]</value>
      <webElementGuid>a594f09d-63c9-4d59-a36b-7060bcdd717d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>e86abfe0-045f-488c-bbd6-d98fd2a429ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/question/category.php?courseid=1159' and @title = 'Categories' and (text() = 'Categories' or . = 'Categories')]</value>
      <webElementGuid>e45d215f-c040-4005-97e3-5fcf7ea23403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
