<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video upload</name>
   <tag></tag>
   <elementGuidId>3b7afbef-77f0-4762-9f60-400cf0a67575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741158894217_2126</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89c5d84f-e210-4a40-8dd5-6e0a6e3279fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ff5c440d-c9f7-4cc1-a6a9-68f4f07c230b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741158894217_2126</value>
      <webElementGuid>f106f5a4-6781-4d29-b3a6-54485195af29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repo_upload_file</value>
      <webElementGuid>b35215e9-fd53-42ad-b149-c5d0fabdbf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.mp4,.webm,.ogv</value>
      <webElementGuid>0a41681d-a54c-4299-b096-4b5d592adf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741158894217_2126&quot;)</value>
      <webElementGuid>4039d599-d41e-4097-8924-6dcdeb6f837d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yui_3_17_2_1_1741158894217_2126']</value>
      <webElementGuid>797e0e63-167f-4d05-9003-c1c5ee0bc4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741158894217_2125']/div/input</value>
      <webElementGuid>bd4ca34e-5b97-4f59-8773-fc378f6b969b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>b73fdf87-925e-466d-9f70-3e7436ddbf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'yui_3_17_2_1_1741158894217_2126' and @name = 'repo_upload_file']</value>
      <webElementGuid>d83e0bb0-94dd-4fbd-a84c-1145c2a03949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
