<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Users_dropdownMenuButton</name>
   <tag></tag>
   <elementGuidId>e4589f48-4783-46b4-9156-289f499cd672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DataTables_Table_5 > tbody > tr.odd > td:nth-of-type(6) > div.dropdown.report_cate_elli_icon > #dropdownMenuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='dropdownMenuButton'])[47]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbf2f441-263d-4f08-8e35-bb7511e42771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>3b85d5a2-f134-441d-b5a0-c8944be55600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>935176d6-98af-40f2-99a7-b8989b854fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton</value>
      <webElementGuid>733da913-7dc7-473e-861f-5f8e9a1733ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>c287a955-3d65-4230-a111-81140ee6dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0912a277-7e37-40ba-9b0e-b2ae38f20e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_5&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;&quot;]/div[@class=&quot;dropdown report_cate_elli_icon&quot;]/span[@id=&quot;dropdownMenuButton&quot;]</value>
      <webElementGuid>c2b4314b-e443-4083-9837-1c983c35ff66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='dropdownMenuButton'])[47]</value>
      <webElementGuid>6d5e59d3-2fa9-4e9e-8482-0eb15bc8772c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_5']/tbody/tr/td[6]/div/span</value>
      <webElementGuid>fe21662f-f26d-4c8d-a32b-d385c1c67e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[20]/following::span[1]</value>
      <webElementGuid>8cde1756-5ea7-49f4-9bad-76a6616afc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon create edit serach delete'])[1]/following::span[2]</value>
      <webElementGuid>ad9fd363-bb47-4089-a552-a17f7f1f0640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[47]/preceding::span[1]</value>
      <webElementGuid>c6e3ae77-b946-446d-a925-1c8ad9860652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[47]/preceding::span[2]</value>
      <webElementGuid>88449789-06a1-4fd1-b56f-143c4cfbc6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/table/tbody/tr/td[6]/div/span</value>
      <webElementGuid>b7ee9c07-f68c-4f96-83ac-0c624f50ae73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'button' and @id = 'dropdownMenuButton']</value>
      <webElementGuid>63e4717b-ada2-4bc5-9f6e-a707ce10b142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
