<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__setting_section_section_5032_included</name>
   <tag></tag>
   <elementGuidId>d5ba4931-83eb-45db-bb77-806cd9f2a32f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_setting_section_section_5032_included']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_setting_section_section_5032_included</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56e4a57a-1ac1-4657-949b-5f56a2372521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>08b455dd-1aae-4986-9cda-28431a286b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>setting_section_section_5032_included</value>
      <webElementGuid>0f24ea1b-5745-47fb-bed7-f111560a5c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aa501c97-b805-4e6f-9e26-6452b2b8d665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_setting_section_section_5032_included</value>
      <webElementGuid>e7026855-ad0b-43e7-86e6-b850a93e6397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_setting_section_section_5032_included&quot;)</value>
      <webElementGuid>75552f46-ffed-4308-8d54-384affc2e941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_setting_section_section_5032_included']</value>
      <webElementGuid>7dba773d-a8fb-4752-876b-cc12757dec13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741164541561_479']/input</value>
      <webElementGuid>c0e825b4-b5a3-4a43-9df5-db0a14cbe234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f79b387a-023e-4177-8183-32a5e3ea704c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'setting_section_section_5032_included' and @id = 'id_setting_section_section_5032_included']</value>
      <webElementGuid>c90476cf-bd07-4b1d-aacc-a4d38137406b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
