<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>02900380-4a32-49a1-93e1-7ff2481e5d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cohort-842 > td:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'2')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d97656a-1116-424f-9937-a14cf7b2c3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/local/learningpaths/cohorts_user_list.php?id=181&amp;lpid=363</value>
      <webElementGuid>dee69d27-36be-461f-bcd0-6e43d4ce978d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6d012c38-e905-4b03-9457-93a5868141a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cohort-842&quot;)/td[4]/a[1]</value>
      <webElementGuid>dec8f580-239a-44ed-9fe6-aa83a12479d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cohort-842']/td[4]/a</value>
      <webElementGuid>00dda42d-efaa-4b0a-b94a-c7c85c4e5c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[3]</value>
      <webElementGuid>5c82cf50-0e10-462d-8234-049b7ceb68ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March 13, 2025'])[4]/following::a[1]</value>
      <webElementGuid>6f09a492-de0c-493f-a328-9027115c29db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon cohort 2'])[1]/following::a[1]</value>
      <webElementGuid>8e21f2c3-4c47-4353-89c9-a68baf0ebabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrollment'])[1]/preceding::a[1]</value>
      <webElementGuid>a27b7e03-b40f-4af7-b31f-b6127f4eed29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification'])[1]/preceding::a[1]</value>
      <webElementGuid>10640af2-044a-4ce5-8662-b61b47f5a360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/local/learningpaths/cohorts_user_list.php?id=181&amp;lpid=363')]</value>
      <webElementGuid>91f19a79-0df7-4286-af48-0a27b4bf643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
      <webElementGuid>e3e7e585-454a-4ffd-ab5d-9440488457fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/local/learningpaths/cohorts_user_list.php?id=181&amp;lpid=363' and (text() = '2' or . = '2')]</value>
      <webElementGuid>adfe8e5e-69b3-42df-9453-ef1405859000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
