<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4</name>
   <tag></tag>
   <elementGuidId>4c625b82-9e7f-4153-9e58-456e14612ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='region-main']/div/div/div/div[2]/div[2]/ul/li[2]/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14ce8968-a9ed-4e4a-922a-7575a46ea0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/local/learningpaths/?userperpage=10&amp;page=3</value>
      <webElementGuid>91537fde-bc06-48d6-b07e-18075186e90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>8123437c-60c4-4b59-965e-db2d4a490b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        4
                    </value>
      <webElementGuid>d7f3a11d-24be-481a-a4e4-be135bdb0cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region-main&quot;)/div[@class=&quot;card card-block content-shadow not-card&quot;]/div[1]/div[@class=&quot;content-title&quot;]/div[@class=&quot;plms-learningpaths p-4&quot;]/div[@class=&quot;mar-btm col-sm-12 mar-no pad-no mar-btm pagination_lp&quot;]/ul[@class=&quot;count_select&quot;]/li[2]/nav[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>dd6917cc-5364-4744-8549-72d09e5dfa7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='region-main']/div/div/div/div[2]/div[2]/ul/li[2]/nav/ul/li[4]/a</value>
      <webElementGuid>ad43f64b-7549-4926-9b27-590fea97e290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'4')]</value>
      <webElementGuid>60afec4a-dbec-45bd-ae72-cce6626fdbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/following::a[3]</value>
      <webElementGuid>e4dada64-0bed-47a8-ad5a-fdd587d108d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[20]/following::a[5]</value>
      <webElementGuid>6cd18e8a-e0af-4251-a410-36f02091c327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[1]</value>
      <webElementGuid>0043914d-f69c-4a82-955b-2e2af42c73c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Side panel'])[1]/preceding::a[2]</value>
      <webElementGuid>7be4d8c6-aa98-4a69-96eb-9197c90615d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>a2e9bec4-5bf5-4749-b3af-a47647c75af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/local/learningpaths/?userperpage=10&amp;page=3')]</value>
      <webElementGuid>5aa3b54a-8857-4ea1-9305-18b6b223bd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[4]/a</value>
      <webElementGuid>014b6c34-5777-4d82-8e50-4d5bebde5e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/local/learningpaths/?userperpage=10&amp;page=3' and (text() = '
                        4
                    ' or . = '
                        4
                    ')]</value>
      <webElementGuid>77197776-9a33-40c8-b947-d4b020237957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
