<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Days After Enrollment_enreminder_edit_da6ddb</name>
   <tag></tag>
   <elementGuidId>ff8c2077-2eee-41bd-9d6e-3b1474d7429a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_enreminder_editor_checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_enreminder_editor_checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a2330a5-7f7e-4df6-b1c5-5846cfee7c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>db6b3b3f-b8bc-4f3f-ba74-e291ad81fada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enreminder_editor_checkbox1</value>
      <webElementGuid>f1b84344-b84a-453f-9fc5-07962b4c01e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2bdfc0b3-069d-4a47-93e6-bf4024937f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_enreminder_editor_checkbox1</value>
      <webElementGuid>857d853f-ecc8-423b-898a-88136595c028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_enreminder_editor_checkbox1&quot;)</value>
      <webElementGuid>d49badb5-7a42-4dd9-a46b-e5d6c363262b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_enreminder_editor_checkbox1']</value>
      <webElementGuid>65ab124a-02f5-43d7-9567-5f39ad8e2cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_id']/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>3d3cf7d5-860a-41b8-8dd5-64901ae8a735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>eeb5bd2d-3fdf-4ba9-8d1c-23d5020b713a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'enreminder_editor_checkbox1' and @id = 'id_enreminder_editor_checkbox1']</value>
      <webElementGuid>739ca024-ff07-4a04-bc0b-e2f532bfc3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
