<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Days After Enrollment_enreminder_editor_text</name>
   <tag></tag>
   <elementGuidId>31c5ec92-fdfb-45e6-9cd4-b096b58d0b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_enreminder_editor_text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_enreminder_editor_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9653d1e4-6ecd-4f3e-9ca0-bb83df7f9c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4be01692-b5d7-46d7-a99a-99e8db4eca24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>97aaddb1-7442-434b-b657-3635929cb072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enreminder_editor_text</value>
      <webElementGuid>fb0836e5-f230-48f2-bc71-c40bc83891ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_enreminder_editor_text</value>
      <webElementGuid>b343c89e-9e4a-4970-ae9d-b9893278393f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_enreminder_editor_text&quot;)</value>
      <webElementGuid>46ca0b6c-f79d-420d-b1ed-641127f36b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_enreminder_editor_text']</value>
      <webElementGuid>5306a47b-6339-4bc8-8344-a90bf4998b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741700533701_2040']/div[2]/div[2]/input</value>
      <webElementGuid>62eda485-1546-479e-a5b2-fd876f181040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>7529c079-5fcb-4005-8da1-50029c8d2903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'enreminder_editor_text' and @id = 'id_enreminder_editor_text']</value>
      <webElementGuid>dfe84f98-a724-4276-b897-d747dfd224ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
