<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Days Before Expiration_completion_rem_db03ac</name>
   <tag></tag>
   <elementGuidId>13382b78-4e0c-4676-a344-caf7c19fdd96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_completion_reminder_editor_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_completion_reminder_editor_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b822d60-ea0a-4ca9-8e6f-3c02ddc8b117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1eba90d-f15d-4722-8acb-4394ffea6ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>c3b7a6d0-e611-41bd-8b69-b904b2040f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>completion_reminder_editor_text</value>
      <webElementGuid>8f872545-6916-4b4d-a137-51b165ed7c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_completion_reminder_editor_text</value>
      <webElementGuid>aca9bd97-e30c-4974-9ade-2b04067f5ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>38196185-cc13-441a-9da3-030c5cfee09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>54913e76-a16f-4c9c-b4d4-df3a38457415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_completion_reminder_editor_text&quot;)</value>
      <webElementGuid>5efe136c-c9bb-467d-8c74-5ccfb339ed24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_completion_reminder_editor_text']</value>
      <webElementGuid>879e0b23-64bf-4425-bdc3-15220fad64ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741700533701_2056']/div[2]/div[2]/input</value>
      <webElementGuid>3a2093af-82a6-450c-8c76-c8ba5bd3f003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>bac11488-6a78-4e69-9e48-a9a184dcf61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'completion_reminder_editor_text' and @id = 'id_completion_reminder_editor_text']</value>
      <webElementGuid>fb92d2c4-8414-45d0-9c2e-8450dc9f0c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
