<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Template_notifications_editor_c_8df1d6</name>
   <tag></tag>
   <elementGuidId>0c1afb9f-9684-43d3-8ebd-625cf5288009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_notifications_editor_checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_notifications_editor_checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b551dbbc-77ef-4b87-aa10-adb4269247f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a1c6b9f1-2b25-48d3-9280-968530235466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notifications_editor_checkbox1</value>
      <webElementGuid>ef87a98e-ca75-4c82-86fe-02c707e7f124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1dfada0e-e139-4aa7-a632-a7c08ecd37a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_notifications_editor_checkbox1</value>
      <webElementGuid>f28e0368-ff64-4986-9b61-dba53344eebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_notifications_editor_checkbox1&quot;)</value>
      <webElementGuid>e0329441-9a8c-4c99-a538-749c2731a2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_notifications_editor_checkbox1']</value>
      <webElementGuid>09f6a65e-6575-437c-8c2c-5ddcf93ea1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741700533701_1876']/div/div[2]/input</value>
      <webElementGuid>ca996a72-9205-4f5d-b023-aea38a535711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>5ceab042-915d-4811-acc5-f7c279a0e006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'notifications_editor_checkbox1' and @id = 'id_notifications_editor_checkbox1']</value>
      <webElementGuid>3ce51fd7-ba5c-4f97-8550-ad94995bf71d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
