<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Days Before Expiration_exreminder_edi_e98544</name>
   <tag></tag>
   <elementGuidId>11e5d42f-8c83-4b8b-83fb-23e3b94a38e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_exreminder_editor_text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_exreminder_editor_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>417c3ee0-d535-498a-8f25-bc339de3a5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec4a6dda-8933-4f76-a2f7-ddc539622ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>c6032e3e-26a0-4b6a-920c-d9a73a4caa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exreminder_editor_text</value>
      <webElementGuid>7e6cb049-ebec-4565-969a-1bf74004ed7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_exreminder_editor_text</value>
      <webElementGuid>e7848715-b897-48be-8e64-f971ff018ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_exreminder_editor_text&quot;)</value>
      <webElementGuid>b79962b9-c2f7-4a3c-8024-e34811495182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_exreminder_editor_text']</value>
      <webElementGuid>92e9e432-9be5-4b83-a589-6875f607e9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741700533701_2048']/div[2]/div[2]/input</value>
      <webElementGuid>73eb7f69-b4bd-4f57-ba51-7d1625e1e289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>9a046988-9b84-4bd9-a0fb-221c3d6aaa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'exreminder_editor_text' and @id = 'id_exreminder_editor_text']</value>
      <webElementGuid>92f6c318-dc7c-4e16-9eec-5a171a72310d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
