<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Days Before Expiration_exreminder_edi_05c6ca</name>
   <tag></tag>
   <elementGuidId>7cf1b014-a472-4aea-aa02-61fc97600e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_exreminder_editor_checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_exreminder_editor_checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f64fea48-9b9a-468f-94b9-1c017a1b1a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bb178bfa-6bcc-4d13-90a0-fc33cde30b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exreminder_editor_checkbox1</value>
      <webElementGuid>e04f36ef-1cea-47ba-b522-7464c547be78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f4fda511-4f3b-4688-92c7-defff847d6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_exreminder_editor_checkbox1</value>
      <webElementGuid>557122b2-8e64-40d4-a0a8-8c1ccd245e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_exreminder_editor_checkbox1&quot;)</value>
      <webElementGuid>86574f54-4ee2-4d40-8daf-3acc6063360a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_exreminder_editor_checkbox1']</value>
      <webElementGuid>1e4bfa00-41d3-4c87-8577-66e837527bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='form_id']/div[3]/div[2]/div/div[2]/input)[3]</value>
      <webElementGuid>3c518d30-15bd-4399-ba21-0e9f81e94617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>ad2042d2-b5df-4454-a0c1-3f096dd9d758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'exreminder_editor_checkbox1' and @id = 'id_exreminder_editor_checkbox1']</value>
      <webElementGuid>cf3f18a0-0cb6-49a9-84a2-b48724460287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
