<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Katalon badge course_403_1</name>
   <tag></tag>
   <elementGuidId>87d68b30-e66a-4f0a-8272-23712bf79ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741700425033_2023</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='yui_3_17_2_1_1741700425033_2023']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9530ac67-2dca-4cfd-bc00-20b3dafa2cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741700425033_2023</value>
      <webElementGuid>89fa6945-ec73-4b69-820a-de3d20943c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon badge course_403</value>
      <webElementGuid>97ea1c6c-720b-492a-b2fc-9dc09f02663e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741700425033_2023&quot;)</value>
      <webElementGuid>624b64e8-deea-4dc0-8207-820a0fa26a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='yui_3_17_2_1_1741700425033_2023']</value>
      <webElementGuid>621d391f-f799-4382-b223-8bc67f5352dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1741700425033_2024']/p</value>
      <webElementGuid>698e97f5-e394-4ea5-8782-c2626681c887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Prerequisites'])[2]/following::p[1]</value>
      <webElementGuid>ed4e34f9-2f72-4ff2-b919-3dfeeb4a50d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::p[1]</value>
      <webElementGuid>897719a7-04fd-46fb-bb53-9222c25c3517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::p[1]</value>
      <webElementGuid>e0d7f26c-595f-4e90-8ed3-4d7451cca348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[2]/preceding::p[1]</value>
      <webElementGuid>34dd7098-69ef-4026-a451-00da843ff819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/form/div[2]/div/div[3]/div/div/div/div/ul/li/span/p</value>
      <webElementGuid>84fab760-f560-4ed1-acad-878a57e2e730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'yui_3_17_2_1_1741700425033_2023' and (text() = 'Katalon badge course_403' or . = 'Katalon badge course_403')]</value>
      <webElementGuid>957f5daf-b5e9-45a6-8550-fadb8a7e5cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
