<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add Activity</name>
   <tag></tag>
   <elementGuidId>92dd50d3-95f3-491f-ab23-c51b54fa20b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='yui_3_17_2_1_1741247685512_587']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741247685512_587</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b9b1c70-3f24-4461-813d-f117239c09c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activity_btn_nm</value>
      <webElementGuid>af7875a0-895d-49b5-b01f-d1fc0ad22091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741247685512_587</value>
      <webElementGuid>ae3727c7-3536-4382-9ade-d68e61fda1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Activity</value>
      <webElementGuid>5852233f-40e7-4c93-9636-c6a9d69ee48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741247685512_587&quot;)</value>
      <webElementGuid>ecedc5ed-83aa-4042-9197-b6aece95263c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1741247685512_587']</value>
      <webElementGuid>b4057ed0-dabd-499e-88fb-e904366a2f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activity_check_1']/span[2]</value>
      <webElementGuid>4dd1c580-8115-4642-9e2a-71b565d143b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file(s) here'])[2]/following::span[3]</value>
      <webElementGuid>3cb5e8e1-885b-40db-b1cc-e595f54ddea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No content added'])[1]/following::span[4]</value>
      <webElementGuid>fb5c56db-0d07-4d9f-9808-1a305ce5de25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/span/a/div/span[2]</value>
      <webElementGuid>14046249-fa02-4a53-87ec-928d267f6069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'yui_3_17_2_1_1741247685512_587' and (text() = ' Add Activity' or . = ' Add Activity')]</value>
      <webElementGuid>046f087b-8b97-44f6-8890-42f0d746235c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
