<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paste_h5p-touch-area</name>
   <tag></tag>
   <elementGuidId>00adc9c2-0fef-4c23-9523-62bd538d4835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h5p-touch-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@class, 'h5p-dragnbar-a') and contains(@class, 'h5p-dragnbar-truefalse-button') and @aria-label='True/False Question']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46e85aaa-3db6-43f4-9ff8-c5eb24a2bec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h5p-touch-area</value>
      <webElementGuid>e592fd0b-3419-4588-893c-fd9521f08ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;h5peditor h5p-interactivevideo-editor&quot;]/div[@class=&quot;h5peditor-form form-manager&quot;]/div[@class=&quot;tree&quot;]/div[@class=&quot;field field-name-interactiveVideo group importance-high wizard&quot;]/div[@class=&quot;h5peditor-panes&quot;]/div[@class=&quot;field interactiveVideo&quot;]/div[@class=&quot;h5peditor-interactions h5p-interactive-video&quot;]/div[@class=&quot;h5p-video-wrapper h5p-video hardware-accelerated&quot;]/div[@class=&quot;h5p-overlay h5p-ie-transparent-background h5p-visible&quot;]/div[@class=&quot;h5p-interaction h5p-truefalse-interaction h5p-dragnbar-element&quot;]/div[@class=&quot;h5p-touch-area&quot;]</value>
      <webElementGuid>77265008-fab5-489a-b7b6-994ea7214893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>56cb5e61-caa2-46bb-a912-282d24701478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
