<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Question</name>
   <tag></tag>
   <elementGuidId>4993a90d-06eb-45fc-a1d1-dfb53a80f6ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field.field-name-question.text.importance-high.html</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Disable image zooming'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bd7a1da-a139-4a4b-a9bc-2310ef6aba76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field field-name-question text importance-high html</value>
      <webElementGuid>9f7e322e-fe08-490b-9fc2-508704c23804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Question</value>
      <webElementGuid>6f0780b1-84a9-42e4-a98f-5be4498f0ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;h5peditor h5p-interactivevideo-editor&quot;]/div[@class=&quot;h5peditor-form form-manager&quot;]/div[@class=&quot;form-manager-form h5p-interactivevideo-editor form-manager-slidein&quot;]/div[@class=&quot;h5p-dialog-inner-semantics&quot;]/div[@class=&quot;field library h5p-truefalse-library&quot;]/div[@class=&quot;libwrap h5p-truefalse-editor no-margin&quot;]/div[@class=&quot;field field-name-question text importance-high html&quot;]</value>
      <webElementGuid>46fc4450-25d3-4684-833f-4a4e6e6471e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disable image zooming'])[1]/following::div[2]</value>
      <webElementGuid>14e0020f-a546-4355-8251-2e8d7dde32e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paste'])[3]/following::div[6]</value>
      <webElementGuid>e5382e97-3e44-4276-ac5b-0eb783f7db57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correct answer'])[1]/preceding::div[3]</value>
      <webElementGuid>e4cf9826-572d-4822-854c-1ab667193723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div[2]</value>
      <webElementGuid>7124306b-c0d1-4eb4-8a08-9696b7e7f41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Question' or . = 'Question')]</value>
      <webElementGuid>33cc45a3-893f-4d5f-85b1-21881f68b666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
