<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Editor_h5p-editor-iframe_1</name>
   <tag></tag>
   <elementGuidId>8a91ecfc-13bb-4596-9eed-99d0a55a130e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.h5p-editor-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mform1_pBW6OKcGmcrgO6c']/div[6]/div[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>57a460e6-eaab-4945-adb4-642f32fbf4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h5p-editor-iframe</value>
      <webElementGuid>cca6f207-5e54-4047-a50a-261968de1ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>310cf5e5-ca7b-4f78-bf74-1795e82520ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>allowfullscreen</value>
      <webElementGuid>60da3d8c-1658-4ccf-af4f-a5189ea41d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen</value>
      <webElementGuid>14454202-0597-4cfa-8882-6956a0aa8a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mform1_pBW6OKcGmcrgO6c&quot;)/div[@class=&quot;form-group row  fitem&quot;]/div[@class=&quot;col-sm-12 col-md-8 col-lg-8 col-xl-8 felement&quot;]/iframe[@class=&quot;h5p-editor-iframe&quot;]</value>
      <webElementGuid>6b77d148-e73d-40f0-b01c-df8e9c685e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mform1_pBW6OKcGmcrgO6c']/div[6]/div[2]/iframe</value>
      <webElementGuid>fa755fcf-302e-460a-8b56-5857d417530f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a8a29620-62a0-40a1-8af8-60fbaf674c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
