<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Used for searching, reports and copyr_b78a23</name>
   <tag></tag>
   <elementGuidId>24209c5a-8425-4e59-ba1a-9409079592e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-extratitle-173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-extratitle-173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d99dbba6-7f8e-402e-ba95-d4bec977868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h5peditor-text</value>
      <webElementGuid>8de19f17-7e90-4d74-8225-90ea1f73d0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e62b986-5d7d-4034-97a3-1d6df1834d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-extratitle-173</value>
      <webElementGuid>2224f6da-50ff-42d9-9eb6-a87c235be76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-extratitle-173-description</value>
      <webElementGuid>d4c6dcc2-d015-4801-a65a-632cb03b0310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>9fcc572b-0f39-4deb-8eb2-e1d63ed9dfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-extratitle-173&quot;)</value>
      <webElementGuid>489e00b9-f403-4df3-bbf6-1c8c6ae807f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Interactive activity in course/Page_Editing Interactive Content/iframe_Editor_h5p-editor-iframe</value>
      <webElementGuid>33ee6fee-5610-4d66-93c3-115e05dd60de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-extratitle-173']</value>
      <webElementGuid>49046f3b-a43e-4268-b996-f525c6d53847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/input</value>
      <webElementGuid>ecbbd777-7fc7-4057-a4c9-195a9db3e939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-extratitle-173']</value>
      <webElementGuid>8321fddb-361a-4d7b-bca8-4fd04fad9b5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
