<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade to pass_gradepass</name>
   <tag></tag>
   <elementGuidId>27319519-3878-49c1-899d-11bf2eb34f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_gradepass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_gradepass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e4f5b99-960e-4b1d-84ce-ce6d2c47d247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e099529-a510-4458-91ac-9de8ffbac51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>2023dcd3-53e7-4356-af34-2ae8bbfbe11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gradepass</value>
      <webElementGuid>7b879f6b-231e-40b3-aed5-a07ec4a9c381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_gradepass</value>
      <webElementGuid>f61b4a9b-3e1e-46b2-9da6-9edcc6fbc010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_gradepass&quot;)</value>
      <webElementGuid>2343ad5e-222d-4496-ab6d-f65b2dcb4d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_gradepass']</value>
      <webElementGuid>30d3539e-d596-4f50-96c6-135a3a31a8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741852823499_1100']/input</value>
      <webElementGuid>c663698c-697a-4080-92c9-2e5f7be3d139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>bf4b691e-5583-4724-a988-2b9c4ffe80b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'gradepass' and @id = 'id_gradepass']</value>
      <webElementGuid>6eaa4ee8-30e2-4642-b51c-26aa3b30444d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
