<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Created manually_icon fa fa-users fa-fw_1</name>
   <tag></tag>
   <elementGuidId>007de819-6c81-4e07-8857-a5fd4e385c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cohorts']/tbody/tr/td[7]/a[4]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-users.fa-fw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>af489042-3f88-4031-9847-1589111c4f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-users fa-fw </value>
      <webElementGuid>320a5c88-6b22-4c3a-af41-a6ab76480836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Assign</value>
      <webElementGuid>d8974829-aad8-4994-b3b5-bc051d799333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Assign</value>
      <webElementGuid>b5ce6fc9-30a5-437b-865c-227880e47aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cohorts&quot;)/tbody[1]/tr[@class=&quot;lastrow&quot;]/td[@class=&quot;centeralign action cell c6 lastcol&quot;]/a[4]/i[@class=&quot;icon fa fa-users fa-fw&quot;]</value>
      <webElementGuid>ecba5326-1b66-4d56-ba90-bdc00a1d6eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cohorts']/tbody/tr/td[7]/a[4]/i</value>
      <webElementGuid>65957ae0-ed48-4e36-acf4-04805c5503d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a[4]/i</value>
      <webElementGuid>37ef8418-88f0-4d01-ac91-1ba649219e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Assign']</value>
      <webElementGuid>aaf46c47-a686-4e7a-9646-c4ec8037201d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
