<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload cohorts_search</name>
   <tag></tag>
   <elementGuidId>d04fc42c-f049-475a-8f30-a9d158945729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cohort_search_q']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cohort_search_q</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>402f4dfe-76ce-4590-bfb0-4b67c6888fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cohort_search_q</value>
      <webElementGuid>3b52d4ac-62e0-4cce-9ab9-53221aff2f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82ed5e15-66bd-499f-9661-a1a04715c271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a1b7e2ed-754b-49ed-aba4-31b63bde0b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mr-1</value>
      <webElementGuid>4cd92578-2876-4396-a52e-82919eb76342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search cohort</value>
      <webElementGuid>fb0ac42c-ff2d-426d-b5e1-00fc0ede833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cohort_search_q&quot;)</value>
      <webElementGuid>b9f7abeb-02da-4d2c-9077-d0ac9e6d51b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cohort_search_q']</value>
      <webElementGuid>245297a3-80c8-4c1d-b5ac-d8776be13423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchcohortquery']/div/div/input</value>
      <webElementGuid>c9835639-e58c-4738-824f-e8d1a5a273eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>b6a2aebf-7883-4481-9494-0d12d9322894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cohort_search_q' and @type = 'text' and @name = 'search' and @placeholder = 'Search cohort']</value>
      <webElementGuid>a5235aa7-0a48-4181-b1ed-fe38abf29ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
