<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Previous_saveanddisplay</name>
   <tag></tag>
   <elementGuidId>0a594038-3606-4bce-9d01-55023b3fd258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnProcess</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'submit' and @name = 'saveanddisplay' and @id = 'btnProcess']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9285164b-e3d2-4cec-80ca-272347c246ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c5fe0c5d-ad12-41c3-8400-84dc914b959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round
                    btn-primary
                    
                    </value>
      <webElementGuid>c0eb3a5c-f908-45fb-84d9-ea7486c653d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>saveanddisplay</value>
      <webElementGuid>f27a575e-db09-4a38-ba9a-1f57b14edfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnProcess</value>
      <webElementGuid>1314f2e4-427c-427c-8f27-9882d9bf7f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>8b26c391-f7de-48f2-bcda-0f1693b0155d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1737460997816_380&quot;)/input[@id=&quot;btnProcess&quot;]</value>
      <webElementGuid>1559c133-3e0e-4b5a-9cc6-7ad2e3a2c95e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnProcess']</value>
      <webElementGuid>19e74025-87df-42f4-b2d0-208b62db90b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1737460997816_380']/input</value>
      <webElementGuid>76040c77-267e-4247-90d9-d375c24c4753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>5c077439-59b4-4199-b84c-b716894408ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'saveanddisplay' and @id = 'btnProcess']</value>
      <webElementGuid>6b80d84c-ebf8-40b4-baa4-e31ee04a6b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1737460469107_380']/input</value>
      <webElementGuid>606b7bea-1b2a-43b9-9cf4-36a033a4372c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
