<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Next_1</name>
   <tag></tag>
   <elementGuidId>0bb6b997-bd24-4251-b100-eedf6d87250e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.btn.btn-primary.btn-round.next-step</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1742907915903_360']/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ff33de0c-2d7c-4ef4-8d2f-56943022bbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-round next-step</value>
      <webElementGuid>a8ee86c3-1f34-4b6c-8bad-90847d7be5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>51a7b986-8008-440c-8e45-ba7e5f6a6183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742907915903_360&quot;)/ul[@class=&quot;list-inline pull-right&quot;]/li[@class=&quot;btn btn-primary btn-round next-step&quot;]</value>
      <webElementGuid>fb2e7817-ba19-4ad8-bdda-20e1fdcbb22f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742907915903_360']/ul/li</value>
      <webElementGuid>0520c103-9aec-47d1-a9f6-8e1e4a56ba06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::li[1]</value>
      <webElementGuid>77a37122-1901-496d-8dcf-dd9c87b594cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Description'])[1]/following::li[1]</value>
      <webElementGuid>5be684f5-80e1-42dc-9b25-9e94c3c9288d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum file size: Unlimited, maximum number of files: 1'])[1]/preceding::li[1]</value>
      <webElementGuid>c7a88c40-e7a3-40cb-9f2e-22a0f46c8726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- drag and drop not supported'])[1]/preceding::li[1]</value>
      <webElementGuid>f09e5c3f-8cd3-46f9-aba9-e12154fa52ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>92fefe93-b2b6-4e42-b75f-07bb40ac6df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>b69e684d-4a7d-4d2e-bf8e-b9c1c8b78bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>c542050f-6f4a-42b3-aa7c-7f22c7c59892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
