<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Katalon Assignment Activity update</name>
   <tag></tag>
   <elementGuidId>63e5225e-13ad-432e-9e9f-b0d63f66777f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1742367362100_668</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Topic'])[1]/following::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>140b382f-db83-49fb-91db-d435db84f65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Katalon Assignment Activity update</value>
      <webElementGuid>b8666861-c03f-4418-9e71-9c8336c93723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1742367362100_668</value>
      <webElementGuid>a1d6ae4a-0a41-4620-9e0c-7868cbf9902e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Assignment Activity update</value>
      <webElementGuid>cb3a1147-ab78-4419-aef8-770d367bfbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742367362100_668&quot;)</value>
      <webElementGuid>5f4c6bad-8d95-4e51-924a-50590c550ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='yui_3_17_2_1_1742367362100_668']</value>
      <webElementGuid>553e4bcb-403a-428a-a50e-e8b11ff0aa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1742367362100_669']/p</value>
      <webElementGuid>6f8e983a-17f3-4c11-a7d2-ba20f87877ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Topic'])[1]/following::p[1]</value>
      <webElementGuid>6b04149f-9dcc-40a5-9af0-fecdee521190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Topic'])[1]/following::p[1]</value>
      <webElementGuid>12dc126a-68ab-4e7b-8293-f3dd7cc2550f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Settings'])[2]/preceding::p[1]</value>
      <webElementGuid>ec480cb4-59f1-44bb-bd0c-e305a535abfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Right'])[2]/preceding::p[1]</value>
      <webElementGuid>d13f775e-dc41-4640-b562-cac63efb060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon Assignment Activity update']/parent::*</value>
      <webElementGuid>68f98435-32a7-4fe3-88c8-0f6ecddee809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/div/div[2]/div/a/span/p</value>
      <webElementGuid>f1242190-c49f-4e42-8d15-5425df7842f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Katalon Assignment Activity update' and @id = 'yui_3_17_2_1_1742367362100_668' and (text() = 'Katalon Assignment Activity update' or . = 'Katalon Assignment Activity update')]</value>
      <webElementGuid>e1205171-ec5c-4427-88a8-db901ae730f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
