<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Learning Path Image_learningpath_imagechoose</name>
   <tag></tag>
   <elementGuidId>33473638-5445-40ae-ace3-30829a026c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filepicker-button-67ceaf4d7a948</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filepicker-button-67ceaf4d7a948']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e96ee1d-2de2-48b9-8dd0-80afa1f90944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaf3d830-3422-4cce-8c44-8049b7645f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fp-btn-choose btn-round</value>
      <webElementGuid>36717523-c2fa-4adc-970c-aebcff856174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filepicker-button-67ceaf4d7a948</value>
      <webElementGuid>66cb5213-07e9-4983-9942-fe247b92a53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Choose a file</value>
      <webElementGuid>8ea91a4d-c713-47bf-b32c-fd67d450846c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>learningpath_imagechoose</value>
      <webElementGuid>19c2ac14-4a25-4f9c-ac58-3a4d95f6cbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepicker-button-67ceaf4d7a948&quot;)</value>
      <webElementGuid>b41926a4-65f4-4e60-8b22-f01889722da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filepicker-button-67ceaf4d7a948']</value>
      <webElementGuid>c75c6690-313b-4dd3-9db8-cff16337c49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741598510139_637']/input</value>
      <webElementGuid>c303382c-c74a-4a7c-baa7-407d98e25e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>0ab7a661-e135-4a57-aa2d-9c15133c1949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'filepicker-button-67ceaf4d7a948' and @name = 'learningpath_imagechoose']</value>
      <webElementGuid>855a98a8-3429-40ed-9489-662789c54479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
