<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add criteria</name>
   <tag></tag>
   <elementGuidId>0c444e64-64f4-4be8-8901-a7f165e0eec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#single_button67f4c229e01c919</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='single_button67f4c229e01c919']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3be405f6-013b-4342-9f06-a02661db856e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d2f8a2aa-6142-4f0a-901e-72dc6d2f36f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-secondary</value>
      <webElementGuid>2b7de785-31dc-4798-a1ba-46522e73d961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>single_button67f4c229e01c919</value>
      <webElementGuid>5a532c26-bba9-4046-9396-b37e5e076190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add criteria</value>
      <webElementGuid>cf473048-9245-4561-9da4-33292885e56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single_button67f4c229e01c919&quot;)</value>
      <webElementGuid>30565aae-a8d6-4758-8b60-d5a4e585e596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='single_button67f4c229e01c919']</value>
      <webElementGuid>74daf34b-1057-480a-8d88-d54e50eefd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='region-main']/div/div/div[2]/div/form/button</value>
      <webElementGuid>4f4bce27-a364-4fd1-ab02-06e75341eac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/following::button[1]</value>
      <webElementGuid>be5826c0-71c5-4928-87e0-da30a76bd439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::button[1]</value>
      <webElementGuid>4db4571c-112f-47e3-9818-a3b63a2c8100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit details'])[1]/preceding::button[1]</value>
      <webElementGuid>8d0f530b-442d-490e-8f1d-084e8333ddac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add criteria']/parent::*</value>
      <webElementGuid>d41f0cb5-5a4f-4ab2-bfd3-ef23d8747626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>ee1ee6fc-7284-4e02-b304-25116aebf1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'single_button67f4c229e01c919' and (text() = 'Add criteria' or . = 'Add criteria')]</value>
      <webElementGuid>5d10a1d7-4c50-48e4-97f1-3fe5742d5d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
