<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Image_imagechoose</name>
   <tag></tag>
   <elementGuidId>c7648964-2d79-43f3-9e3d-5459e9a9d664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filepicker-button-67e11c4a69fd3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9181267f-5453-4582-8786-1d5dcaa1b41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a056e199-6966-4d85-8700-a735c2f5837a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fp-btn-choose btn-round</value>
      <webElementGuid>dea6c48a-0114-48fc-a6b5-537895941de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filepicker-button-67e11c4a69fd3</value>
      <webElementGuid>02f1ea3b-2bd0-4159-9e9b-f0289f7b64b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Choose a file</value>
      <webElementGuid>5f23667e-7e35-4da1-a5e8-53687b218108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>imagechoose</value>
      <webElementGuid>24a7571b-8883-4e40-9d74-d311094f6138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepicker-button-67e11c4a69fd3&quot;)</value>
      <webElementGuid>014638a9-84fe-42da-81e9-6e7e7edbc410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filepicker-button-67e11c4a69fd3']</value>
      <webElementGuid>60523ca6-a29f-4c0d-bc37-c4e67d2230af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742806038182_315']/input</value>
      <webElementGuid>dfde220b-6db7-408b-ae92-a2499a6b4eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>b16b0c34-5b14-4495-8a09-1cee17e12dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'filepicker-button-67e11c4a69fd3' and @name = 'imagechoose']</value>
      <webElementGuid>b66b68af-2824-49cc-beb1-babf6e3cb024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
