<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Image_imagechoose</name>
   <tag></tag>
   <elementGuidId>c7648964-2d79-43f3-9e3d-5459e9a9d664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filepicker-button-67e11c4a69fd3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>130ff231-6c0a-4a4b-a3d6-f2e2606f76fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4a7c66a-3480-46ce-9efe-bfb1e34c2e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fp-btn-choose btn-round</value>
      <webElementGuid>8be520b0-a0d2-4eb1-b677-c18c24da5e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filepicker-button-67e11c4a69fd3</value>
      <webElementGuid>6c2bf921-fa1f-4c60-81fb-7289a6d933e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Choose a file</value>
      <webElementGuid>c4f7c385-44b1-49fa-a624-502118c6fa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>imagechoose</value>
      <webElementGuid>03389bbf-4d45-4574-a32c-0385d34fca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepicker-button-67e11c4a69fd3&quot;)</value>
      <webElementGuid>ffbfdcc5-e00c-412d-b8af-ad22b1dae688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filepicker-button-67e11c4a69fd3']</value>
      <webElementGuid>45829adb-db36-4b80-b084-657e5e2f687e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742806038182_315']/input</value>
      <webElementGuid>772dd9aa-2071-400f-8eae-e25875c6f979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>3b27b587-5018-4b91-a25c-1379bf20b018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'filepicker-button-67e11c4a69fd3' and @name = 'imagechoose']</value>
      <webElementGuid>6c85ec44-fcfb-4652-8392-7ab8ac9b0026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
