<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Topic_appendsection</name>
   <tag></tag>
   <elementGuidId>5a6fec21-36bb-4ee8-8e08-aa2fb16665b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;appendsection[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='appendsection[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>754cf607-abc9-4d1a-8472-f480f6834e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a50893cd-9050-42e4-b62b-85f2334468b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control appendsectioncls</value>
      <webElementGuid>91ac95f6-a61c-4029-990d-016c5bafb9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appendsection[]</value>
      <webElementGuid>1b743a53-0e29-4d09-b55c-15b748cea3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Topic Name (Topic 1)</value>
      <webElementGuid>50684c15-e7e8-4851-a568-a291f4e59327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742192358437_569&quot;)/div[@class=&quot;append_topics&quot;]/div[@class=&quot;form-group&quot;]/div[1]/input[@class=&quot;form-control appendsectioncls&quot;]</value>
      <webElementGuid>c0fc92f2-421e-4192-8af6-b46db4b0d444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='appendsection[]']</value>
      <webElementGuid>e5951781-5f5f-48ea-902d-04e7132186a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742192358437_569']/div/div/div/input</value>
      <webElementGuid>ab162169-d5e6-4270-9603-2d70fa4cd12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/input</value>
      <webElementGuid>cff8623e-b005-45d0-9e9f-403e2718c017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'appendsection[]' and @placeholder = 'Enter Topic Name (Topic 1)']</value>
      <webElementGuid>80f21161-d489-43b8-a2f0-d59d02dd9e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
