<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Topic_appendsection_1_2</name>
   <tag></tag>
   <elementGuidId>0bbbc9c5-9d7b-4d60-ae0d-da8128a19e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='appendsection[]'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed0a310c-270a-4771-9c78-aecc9edd9266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>825ab193-ef76-409b-a645-bb6e6fbcd504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control appendsectioncls</value>
      <webElementGuid>07bc2bda-a6dd-4bf6-8aaf-2ee32aec10f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appendsection[]</value>
      <webElementGuid>9e7a6407-7318-48e4-affa-637b19d91dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Topic Name (Topic 2)</value>
      <webElementGuid>708f465d-a76d-45b1-ad5b-b355d748c5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742192358437_584&quot;)/div[@class=&quot;form-group&quot;]/div[1]/input[@class=&quot;form-control appendsectioncls&quot;]</value>
      <webElementGuid>9ce2a469-797a-4176-8258-9db1d3f4d258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='appendsection[]'])[2]</value>
      <webElementGuid>40d90596-9282-4bff-9b20-37a51d5c7e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742192358437_584']/div[2]/div/input</value>
      <webElementGuid>849d18c8-3e9b-4067-9139-a97524e6b2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>9174805b-1bbd-4fbf-9789-c7476bfd7157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'appendsection[]' and @placeholder = 'Enter Topic Name (Topic 2)']</value>
      <webElementGuid>bfb4723f-9306-4f50-ad63-7371e01e5da5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
