<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of Topics_add_section_numsections</name>
   <tag></tag>
   <elementGuidId>04a42a8b-36ef-45d9-b021-576237a23b56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_section_numsections</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add_section_numsections']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd2a4b5b-4bf0-462c-b386-c2696b01c7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_section_numsections</value>
      <webElementGuid>72e40c4e-d669-4ac0-9f07-d0f1d92041cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d9ca4935-778d-4fdd-8a7b-40169e6ee1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8cce9d3a-cb6c-4256-93f5-d3fe2baf7b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>73d18c96-2160-401e-9c2b-e22df39afe8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>009e4531-eefb-4686-9a0e-0b5b750febb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_section_numsections&quot;)</value>
      <webElementGuid>68f61ee0-c43f-4c61-b83f-ae8d0df02a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add_section_numsections']</value>
      <webElementGuid>90686a28-585a-4555-b4d3-7ecbd911ff4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742192358437_569']/input</value>
      <webElementGuid>5e621f71-a67f-4045-b65a-6f1470c665c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/input</value>
      <webElementGuid>80992749-8db8-4aa2-a16a-79ac75cb1caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add_section_numsections' and @type = 'number']</value>
      <webElementGuid>76affbbc-335c-42b8-afbd-74ed28563e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
