<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Topic_appendsection_1</name>
   <tag></tag>
   <elementGuidId>1e590b1e-5373-41c8-8a11-d5e5b2efb3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and contains(@class, 'appendsectioncls') and @name='appendsection[]' and @placeholder='Enter Topic Name (Topic 1)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1742192358437_581</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>509775ca-ab3f-4407-be49-52c1a98f9c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a54cd247-6662-4346-a437-05235c64d881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control appendsectioncls</value>
      <webElementGuid>9fd235b0-9cf4-4884-a277-c307e39de391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appendsection[]</value>
      <webElementGuid>74e6f869-b6f3-4264-8725-1f1bb215a74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Topic Name (Topic 1)</value>
      <webElementGuid>4fcd288a-5624-4a0c-87f6-360ee5528d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1742192358437_581</value>
      <webElementGuid>e1233829-95e6-4f2c-87a4-e68055400dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742192358437_581&quot;)</value>
      <webElementGuid>5679826b-141e-4bce-a5a3-8216f4029088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yui_3_17_2_1_1742192358437_581']</value>
      <webElementGuid>de6fe1e2-3b33-45c0-92e5-29772c731ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742192358437_582']/input</value>
      <webElementGuid>292751e4-5fd6-437c-bc18-2f8725d9ab41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/input</value>
      <webElementGuid>6708d312-b874-47f4-9c18-ab024e1470e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'appendsection[]' and @placeholder = 'Enter Topic Name (Topic 1)' and @id = 'yui_3_17_2_1_1742192358437_581']</value>
      <webElementGuid>fe8388d6-da9d-4a45-b5aa-f686d3cd1b97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
