<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Site AdminNo Rolesguestuser</name>
   <tag></tag>
   <elementGuidId>06984080-5aba-4b7e-8cb3-c424873ef670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='yui_3_17_2_1_1738831020027_38']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1738831020027_38</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;××Site Admin×No Roles×guest×user&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>7ef62dfc-e37e-483f-b6de-6c82b0a3e5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1d86f186-5629-4a01-ab83-ae5818443594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1738831020027_38</value>
      <webElementGuid>736af9da-c888-4943-b725-5d935642366f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>××Site Admin×No Roles×guest×user</value>
      <webElementGuid>9a13d032-9b36-4212-be34-c89b75479424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1738831020027_38&quot;)</value>
      <webElementGuid>93838ca9-fb3a-4b8e-ac80-791bbcbfd845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='yui_3_17_2_1_1738831020027_38']</value>
      <webElementGuid>9cd76a72-0e84-4fd3-9119-7b54736bf0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1738831020027_39']/ul</value>
      <webElementGuid>07dc7a5a-b586-4d3f-beeb-aa866d476835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Roles'])[1]/following::ul[1]</value>
      <webElementGuid>70c5c03e-4eeb-4bf3-a4a9-954d5f4e2b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul</value>
      <webElementGuid>2bdb36eb-91ae-41a1-83c0-5427487a9aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'yui_3_17_2_1_1738831020027_38' and (text() = '××Site Admin×No Roles×guest×user' or . = '××Site Admin×No Roles×guest×user')]</value>
      <webElementGuid>167fe556-fb39-4f26-a4bc-846f5be17c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
