<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>a5e0585d-28cc-4742-b59d-f852dc095aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741853187465_642</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='yui_3_17_2_1_1741853187465_642']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fcbdb0bf-9a5b-42f1-89fc-8bf74a7b14bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/course/mod.php?sesskey=ztuSA3R6Et&amp;sr=0&amp;delete=9704</value>
      <webElementGuid>57ee348a-d40f-42ee-b81b-664149ba7661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item editing_delete menu-action</value>
      <webElementGuid>52dcb516-56ee-4028-a208-e9d7ae86ded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>b74506c7-7243-434a-aea8-c7c87c8e43f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sectionreturn</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2d53202e-09d5-4e86-8bce-34ebd6f5c3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1f458e9f-c7cc-44da-8ca5-580355129e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>actionmenuaction-21</value>
      <webElementGuid>9b4f796a-d5dd-4d5b-ba1b-163d0fa1aedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741853187465_642</value>
      <webElementGuid>d2d9c504-82b0-4571-8714-8bbd25ed0dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            Delete
    </value>
      <webElementGuid>1888ca0e-9ed2-4116-9e7d-f76b52a81322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741853187465_642&quot;)</value>
      <webElementGuid>a2fd149b-9daf-44d1-a26b-54a0eefb155a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1741853187465_642']</value>
      <webElementGuid>2f52a1ed-a2cf-4d47-bf77-83efcba70f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-menu-4-menu']/a[8]</value>
      <webElementGuid>c827ea56-08d1-437f-a982-68cf3fb49fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Roles'])[2]/following::a[1]</value>
      <webElementGuid>55ac51ca-a183-4fd1-9fad-42570adba0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Groups (Click To Change)'])[2]/following::a[2]</value>
      <webElementGuid>2695679b-b642-45dc-b961-de81792db1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Students can manually mark this item complete: Katalon Title update'])[1]/preceding::a[1]</value>
      <webElementGuid>60ecdada-9a94-424b-ae5f-57d0a1e43c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=ztuSA3R6Et&amp;sr=0&amp;delete=9704')]</value>
      <webElementGuid>8ca8e7d1-1427-419a-8a57-8295ca8f1283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/div/div[2]/span/div/div/div/div/a[8]</value>
      <webElementGuid>fcf466aa-7d5a-426d-86e0-dbc0a2ba40bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=ztuSA3R6Et&amp;sr=0&amp;delete=9704' and @id = 'yui_3_17_2_1_1741853187465_642' and (text() = '
            
            Delete
    ' or . = '
            
            Delete
    ')]</value>
      <webElementGuid>8d73595d-b833-433f-8aa5-5bf3ff60cc4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
