<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Container_fa-type</name>
   <tag></tag>
   <elementGuidId>6d4b4653-0686-454d-81de-36b7d9332835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fa-type-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fa-type-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Select Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93dd0a84-99e2-48ec-b3d3-b77a1b5a1b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Icon</value>
      <webElementGuid>fd6cc8c9-6315-4452-a06a-d622475a0b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a77c2077-dcff-4ad8-a014-5a0dd2fc90a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5857f3f0-a4e7-48e0-97e9-a30eef03488c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fa-type-text</value>
      <webElementGuid>37c758f5-9bf2-4c49-ba76-61dc4141c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fa-type</value>
      <webElementGuid>d94b1445-d3f4-40f9-b704-ebb6b9a424b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fa-type-text&quot;)</value>
      <webElementGuid>3c7c258a-155f-4ba9-b1ff-5fb82776b5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fa-type-text']</value>
      <webElementGuid>0656b2d3-e18f-4818-8435-84ec271db7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fa-type']/div/input</value>
      <webElementGuid>d5c95983-1f15-4a81-b1e9-05389ec82c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>7e40a11a-5d09-4db5-90ef-2635f831bafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Select Icon' and @type = 'text' and @id = 'fa-type-text' and @name = 'fa-type']</value>
      <webElementGuid>474c7638-9eba-450b-8222-2d3a4d954020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
