<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_type</name>
   <tag></tag>
   <elementGuidId>fb8896c6-1509-4adb-8cfd-9dcd1fdfc482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Link&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18321afd-32fa-402e-8180-6c4570c412dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-check-input</value>
      <webElementGuid>9bdac024-e5be-4539-800c-fe01df2ada9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type_link</value>
      <webElementGuid>f50bad36-0743-40e1-9984-2d59a24e0131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0e3b591c-5324-456e-bf2f-4cd2dfc459bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a709b541-91f4-49cc-bbeb-4b5d013876f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>3c157139-3328-44a2-92d9-200f97015a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>a889f17f-99ff-4aa8-a4a1-ed95f3b056eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type_link&quot;)</value>
      <webElementGuid>9724bdd5-3eef-4d02-85c8-e4f6111d3d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type_link']</value>
      <webElementGuid>bf9140bb-f262-401d-b12c-4ee6e61847cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1739163566904_14']/div[2]/div[2]/div[2]/form/div/div/input</value>
      <webElementGuid>ac2acdde-ff8f-400e-b8ee-078e0930765a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>35328212-a6af-4766-a3d0-82785c8bf819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'type_link' and @type = 'radio' and @name = 'type']</value>
      <webElementGuid>bc3a212e-a16f-4d88-9c08-fa77643872c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
