<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Link_menu-dots-vertical_1_</name>
   <tag></tag>
   <elementGuidId>44586943-a20c-40d2-9b4a-6dd20812bec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuOptionsmenuItem_267 > #menu-dots-vertical_1_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menuOptionsmenuItem_267</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4cb296d6-3be9-4437-8b51-b5b174b0eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-dots-vertical_1_</value>
      <webElementGuid>153afd84-4726-43dd-b9ba-322b6f848691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>menu-dots-vertical (1)</value>
      <webElementGuid>640b21cd-c15a-424f-97ae-babbd64a9b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>85377918-445c-4133-8b60-ebcb6a504a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>710d5bf2-04c9-416a-aefc-463cf1c5f286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>da2e895c-e156-4f7e-9e87-d013904a0696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 4 20</value>
      <webElementGuid>f4181ab9-d8e1-4d0a-b7f2-05fe4fce0d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuOptionsmenuItem_267&quot;)/svg[@id=&quot;menu-dots-vertical_1_&quot;]</value>
      <webElementGuid>19399fad-8544-4b79-acda-144df93813c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>11721095-7cb1-466b-b24b-bf2a59c8afab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>cda7a325-aa58-4b38-82a3-02581afe0564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>82352fcb-8ed7-4a2b-b3d1-10ff7a5d4d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>51c4c4eb-3851-44a8-9e27-896690954249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'menu-dots-vertical_1_']</value>
      <webElementGuid>19973ea7-800e-4099-b766-4ae61c1076a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
