<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>d0cb9836-e8ff-4b1d-936a-fd8105196d2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reports-columns-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reports-columns-add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef6ed1f0-eff5-4672-9316-0a45fb83d07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reports-columns-add</value>
      <webElementGuid>91d35bdc-7a02-4b12-84eb-06c48a9aa6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-primary new-btn-rnd btn-report-editp</value>
      <webElementGuid>2029f3b2-f59e-454b-85ac-292cdca28801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add </value>
      <webElementGuid>01c7fa8b-c5e6-4112-8c1e-9d080973ca23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reports-columns-add&quot;)</value>
      <webElementGuid>0c46f567-65af-45c3-b227-b923318a7aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reports-columns-add']</value>
      <webElementGuid>e1ed7831-72b5-4645-b76f-600d39bf98f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741261386584_65']/button</value>
      <webElementGuid>5526aeba-30ec-4cdb-b8f6-748fc0d17b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[[help_learningpath_required_courses]]'])[1]/following::button[1]</value>
      <webElementGuid>38ceb9f3-d9ea-4a2f-bfe9-56995ae47438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[[help_learningpath_total_cohorts]]'])[1]/following::button[1]</value>
      <webElementGuid>1addc177-92a6-469c-bb68-6ebb158b9b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>7d45d6ce-0c80-4a39-80e6-a28d1c5e72aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Columns currently in the report'])[2]/preceding::button[2]</value>
      <webElementGuid>17b419bf-d27c-4025-88b9-20e7f09205e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>80c225ca-82a6-41f3-a8bb-492dc3dcf404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/button</value>
      <webElementGuid>79f292d8-174f-4a54-b635-b41e7b037d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reports-columns-add' and (text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>5d14b1df-249b-41fd-a38a-80776015c588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
