<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Awarded by Manager_dropdownMenuButton</name>
   <tag></tag>
   <elementGuidId>12c7dc89-f24c-4608-8322-d1b90f7f83b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//i[@id='dropdownMenuButton'])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.lastrow > td.actions.cell.c4.lastcol > #dropdownMenuButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e6595545-6127-4d29-9c98-c2a25b043cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-v</value>
      <webElementGuid>aa6d5aad-1d35-49f2-adf3-d69567baab37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b08862e9-b616-481e-8050-d436afcbc709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton</value>
      <webElementGuid>be0aea53-b601-452d-9bd5-b50b9b4bf9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>a5e49cac-54bf-42c0-b407-f00b30dba4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>598ca81c-0bb0-44f8-987a-b5b1b73b901f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742559538907_22&quot;)/table[@class=&quot;table table-bordered table-striped&quot;]/tbody[1]/tr[@class=&quot;lastrow&quot;]/td[@class=&quot;actions cell c4 lastcol&quot;]/i[@id=&quot;dropdownMenuButton&quot;]</value>
      <webElementGuid>19ca6d6e-c543-449c-b667-2a7f532acabc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//i[@id='dropdownMenuButton'])[17]</value>
      <webElementGuid>9b9b91da-f527-4206-8679-d4ca4821261b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1742559538907_22']/table/tbody/tr[17]/td[5]/i</value>
      <webElementGuid>7cc43ec2-ea10-4c3f-914e-6482c95f8116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[5]/i</value>
      <webElementGuid>81cae26d-e71f-4a9b-90e9-b420ad21e1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@type = 'button' and @id = 'dropdownMenuButton']</value>
      <webElementGuid>56c619c3-0ff1-41a7-8098-f649a645b19e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
