<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Answer 2_answer1</name>
   <tag></tag>
   <elementGuidId>88ceaee1-8b2b-49a1-9935-150e10bd85d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_answer_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_answer_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f82906c7-6a00-449b-9836-16952b22e111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>343612d6-b3c0-4e3c-bc94-2abedce563eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>7337734a-6500-4ac7-865b-32a32897d7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer[1]</value>
      <webElementGuid>11581da4-c414-4d13-a918-2ce0ea33161b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_answer_1</value>
      <webElementGuid>ae71f4e4-c449-47f9-b1ce-4f7dc61affaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>bc3948de-5255-425f-b9af-6d0567c152b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_answer_1&quot;)</value>
      <webElementGuid>225efa20-b0ec-4680-978c-552ec2dcf6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_answer_1']</value>
      <webElementGuid>5fb30b44-6488-4e43-b1db-61f5d4f7f2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1743138336483_3235']/input</value>
      <webElementGuid>c3364e36-decd-4dc0-a2c5-b1b2dfb4080c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[2]/div/span[2]/input</value>
      <webElementGuid>4668f949-fce5-45eb-a020-e835d4863292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'answer[1]' and @id = 'id_answer_1']</value>
      <webElementGuid>2c0b207b-c10c-4041-b262-b3676602072e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
