<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_None            100            90   _353130</name>
   <tag></tag>
   <elementGuidId>8739005b-98a0-4661-b30a-df1d8ddd7656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_fraction_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_fraction_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>059aaa71-1c5b-4523-a288-ad44cd23864d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>17a95909-9b38-4ba5-8da5-b647c5e58a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraction[0]</value>
      <webElementGuid>bda24923-e3c6-4d6b-8b2f-a37ec09f91bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_fraction_0</value>
      <webElementGuid>901d990d-085e-42fc-87f4-c825c658f4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            None
            100%
            90%
            83.33333%
            80%
            75%
            70%
            66.66667%
            60%
            50%
            40%
            33.33333%
            30%
            25%
            20%
            16.66667%
            14.28571%
            12.5%
            11.11111%
            10%
            5%
        </value>
      <webElementGuid>9c874729-dbe0-4aff-9e8f-dc62a66d9729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_fraction_0&quot;)</value>
      <webElementGuid>2a8f8c99-3164-441b-9ae4-dc7cc70be2e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_fraction_0']</value>
      <webElementGuid>441ec218-2e73-4a09-9ade-92059cbb51ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1743138336483_3228']/select</value>
      <webElementGuid>861f1103-f83d-4555-9518-01b0c3fc78e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/following::select[1]</value>
      <webElementGuid>dc7d5213-f3d3-4e3d-b7de-2e3cdb7604c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::select[1]</value>
      <webElementGuid>13bfe6e4-f3c6-4d05-a81f-3c7c61abf7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::select[1]</value>
      <webElementGuid>150544e5-5e5c-47d7-b0fa-8e8a7df9bc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer 2'])[1]/preceding::select[1]</value>
      <webElementGuid>6329f475-a5a2-49dc-a50c-96427898d98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>d028f31e-c784-4504-8ed5-42ee547cc3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fraction[0]' and @id = 'id_fraction_0' and (text() = '
            None
            100%
            90%
            83.33333%
            80%
            75%
            70%
            66.66667%
            60%
            50%
            40%
            33.33333%
            30%
            25%
            20%
            16.66667%
            14.28571%
            12.5%
            11.11111%
            10%
            5%
        ' or . = '
            None
            100%
            90%
            83.33333%
            80%
            75%
            70%
            66.66667%
            60%
            50%
            40%
            33.33333%
            30%
            25%
            20%
            16.66667%
            14.28571%
            12.5%
            11.11111%
            10%
            5%
        ')]</value>
      <webElementGuid>d7f56797-2a67-4824-b105-73908947621f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
