<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Katalon_Activity_search_img_content</name>
   <tag></tag>
   <elementGuidId>608a396f-54d5-4889-878b-24734584384f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1741600386001_43']/div[2]/div/div[2]/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.search_img_content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d59c3ac-0623-43f2-9d24-990ab68bfab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/pluginfile.php/53255/course/overviewfiles/course_default_2.png</value>
      <webElementGuid>62dce466-be19-4b96-b514-071d9d476a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Demo Course</value>
      <webElementGuid>dac27ad4-bde5-475d-ba1c-328e632d1292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_img_content</value>
      <webElementGuid>aab6e910-3d97-412a-be6f-83b9afd6a521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741600386001_43&quot;)/div[@class=&quot;course_search_popup_data&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 course_search_div p-0&quot;]/div[@class=&quot;row course-list&quot;]/div[@class=&quot;row card-box&quot;]/div[@class=&quot;img-wrap&quot;]/a[1]/img[@class=&quot;search_img_content&quot;]</value>
      <webElementGuid>183577e9-2b9c-4e0e-b19e-0a1cd41e7d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741600386001_43']/div[2]/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>940b1f8a-aaa4-4cae-8ec4-fad7bed16034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Demo Course']</value>
      <webElementGuid>d8370d35-88cb-40dc-a8fc-606f1868b079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>faed66ca-6f5d-4ea7-82f6-6e9850ff5b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://plms-php81.paradisolms.net/pluginfile.php/53255/course/overviewfiles/course_default_2.png' and @alt = 'Demo Course']</value>
      <webElementGuid>bad727af-451a-4394-8169-1963fe9d1b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
