<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload Scorm</name>
   <tag></tag>
   <elementGuidId>36dd8432-9056-4386-89c1-74ff8394dc56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-file-o.fa-fw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@title='Add...'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fc3e13d0-dda3-47ad-bff3-6fbcd8ea3832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-file-o fa-fw </value>
      <webElementGuid>ddba19c8-9979-46ae-b430-00d905ae82a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b04cc3a8-d296-4144-b896-5c2f5b4661af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filemanager-67c9863333b5d&quot;)/div[@class=&quot;fp-navbar bg-faded card m-b-0&quot;]/div[@class=&quot;filemanager-toolbar icon-no-spacing&quot;]/div[@class=&quot;fp-toolbar&quot;]/div[@class=&quot;fp-btn-add&quot;]/a[@class=&quot;btn btn-secondary btn-sm&quot;]/i[@class=&quot;icon fa fa-file-o fa-fw&quot;]</value>
      <webElementGuid>c77fef3d-10ba-4d7b-b937-9bddb30ad751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filemanager-67c9863333b5d']/div[2]/div/div/div/a/i</value>
      <webElementGuid>98671fef-b512-4038-8495-f4f62d6da197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div/div/div/a/i</value>
      <webElementGuid>145da933-3788-4093-b558-358933e723c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
