<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label_label</name>
   <tag></tag>
   <elementGuidId>59758150-54fe-435f-8459-a883759ca88d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#label_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='label_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ad75646-1171-4f62-812a-fbb0fcc02523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36b0bf25-6cf0-411c-a005-2cf552d965b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label_id</value>
      <webElementGuid>b3fad237-7be3-4c98-9cd1-a6a8b262ae3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9507367e-c45f-4241-8d5a-785b81aeac2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>59ecaa50-e887-4c8c-a091-6d39239759f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label_id&quot;)</value>
      <webElementGuid>3bc8220c-55c8-43df-9a4b-5f82a4668787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='label_id']</value>
      <webElementGuid>4dc75c41-af64-4d74-8d3b-299b0e4ee5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plms-course-wizard1']/div/div[2]/input</value>
      <webElementGuid>a5d6c58f-86e6-4797-9f2e-dac3b3924c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/input</value>
      <webElementGuid>49c8c426-6f4a-424d-800a-bd903c9e096c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'label_id' and @name = 'label']</value>
      <webElementGuid>4a8c05a5-8d1b-40bf-8b61-e16bc84326f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
