<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Course completion_mustbecompleted</name>
   <tag></tag>
   <elementGuidId>f13e97b7-9513-4f3f-a951-f423891013fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_mustbecompleted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_mustbecompleted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecb8c771-751f-4419-85ff-f23b0d5c9ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>66a3f6ee-050b-44fa-a5d2-73e1e57d95c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mustbecompleted</value>
      <webElementGuid>922eb5ed-409d-4494-bc71-e70a2b1e08a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>442867bf-5bfd-4a69-939a-a2e21a034541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_mustbecompleted</value>
      <webElementGuid>39401a84-01e0-4e6d-a6b7-7e52eccea9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_mustbecompleted&quot;)</value>
      <webElementGuid>b857d50b-482d-492d-b8aa-87457ad582e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_mustbecompleted']</value>
      <webElementGuid>08e26887-0e9f-4d90-8257-0542d45892e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741854543610_1931']/input</value>
      <webElementGuid>24d3ba2e-c2fd-421e-baae-ead98d307b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>a8bf883e-7e7a-429b-beff-bfadff67faa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'mustbecompleted' and @id = 'id_mustbecompleted']</value>
      <webElementGuid>508567ea-c9fa-4d98-a3ac-509411f4bb20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
