<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Automatic            Embed          _3fa1fd</name>
   <tag></tag>
   <elementGuidId>2d9b2be5-6526-415b-a49c-d4d46b1b51c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_display']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d128e3d4-10c1-42bd-8d11-1e03db44ef06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b588613f-719a-44ea-ac05-00797a6bc060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>display</value>
      <webElementGuid>dc7ed2dc-c847-46f3-8d99-472e13f601e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_display</value>
      <webElementGuid>da3d74f8-fec7-4bae-9401-92899cdbe453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Automatic
            Embed
            Open
            In pop-up
        </value>
      <webElementGuid>4a42eac6-7249-40a5-ae33-4cbb5ebbc775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_display&quot;)</value>
      <webElementGuid>b0669c0b-0a2e-4f91-aa2b-910a0f6c5e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_display']</value>
      <webElementGuid>f2bb7c26-7483-423c-8343-8fd095b2de3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741247713632_1042']/select</value>
      <webElementGuid>cc9ae20c-12a6-4c94-8b5c-a510a829a0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display'])[1]/following::select[1]</value>
      <webElementGuid>6cfbee0c-a388-4e9f-8622-df2fc8599409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pop-up width (in pixels)'])[1]/preceding::select[1]</value>
      <webElementGuid>f16415af-bd17-4634-98ce-d9a83024e74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pop-up height (in pixels)'])[1]/preceding::select[1]</value>
      <webElementGuid>5bf24069-d18e-4a16-ab5d-73116a134405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>63fb1a54-60f8-4b7c-854b-28c46cfec664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'display' and @id = 'id_display' and (text() = '
            Automatic
            Embed
            Open
            In pop-up
        ' or . = '
            Automatic
            Embed
            Open
            In pop-up
        ')]</value>
      <webElementGuid>4c16642f-9930-48de-bdb1-04bc86539987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
