<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_a new question_1_2</name>
   <tag></tag>
   <elementGuidId>7b040bbc-9740-486f-a5f8-f2384276efff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionmenuaction-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-action='addquestion']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4807472d-e97e-495a-b820-27a279a1043f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-action-text</value>
      <webElementGuid>bd2b2e83-4556-4503-adfe-a1eacc56a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionmenuaction-9</value>
      <webElementGuid>7d881264-7949-45a7-bf29-f76a54981ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a new question</value>
      <webElementGuid>3b8d6f19-1cc5-4e5b-8bb9-dd890c5ac47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionmenuaction-9&quot;)</value>
      <webElementGuid>2a69c680-8e72-4e2a-bfd9-f0da8380bb1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionmenuaction-9']</value>
      <webElementGuid>caf5cc12-e363-402d-ae39-27bfb7b02df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1743138321790_451']/span</value>
      <webElementGuid>486cc35e-2593-4455-b661-6b6e0c374e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[3]/following::span[1]</value>
      <webElementGuid>f932859a-b4d2-4d90-bb0a-cc4337e08d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon multiple choice question'])[1]/following::span[8]</value>
      <webElementGuid>29b2d600-b53d-4138-876e-80f1b6ea1213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from question bank'])[3]/preceding::span[1]</value>
      <webElementGuid>c01eb9a3-7fbf-403d-8da1-3619b8e7d145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a random question'])[3]/preceding::span[2]</value>
      <webElementGuid>1002a8b6-b407-4db0-a656-8a577abad29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/div/div/div/a/span</value>
      <webElementGuid>85bc2584-8a60-43c9-a6ea-308cabb9fe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionmenuaction-9' and (text() = 'a new question' or . = 'a new question')]</value>
      <webElementGuid>7b898550-3ab4-4153-ad74-ca3880a444e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
