<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_a new question_1_2_3</name>
   <tag></tag>
   <elementGuidId>70081d9f-d3aa-4f53-ad4a-df28aaa2b00e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionmenuaction-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(), 'a new question') or span[contains(text(), 'a new question')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>432bfe43-3e2b-48f9-ac18-fd1250647741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-action-text</value>
      <webElementGuid>dee5f162-4404-4515-a5a4-21a6af90cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionmenuaction-13</value>
      <webElementGuid>e3e45feb-b366-4ae4-b315-d3f06db1daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a new question</value>
      <webElementGuid>76da869c-63ea-40fe-b78d-1d339b8828fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionmenuaction-13&quot;)</value>
      <webElementGuid>03b93424-97c2-4e26-820d-d6fc35e0bdfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionmenuaction-13']</value>
      <webElementGuid>e0e8ded5-1fb2-4e6a-8d65-10eac247f436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1743138388692_477']/span</value>
      <webElementGuid>f62ad805-015e-4668-95af-05f2daec4fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[4]/following::span[1]</value>
      <webElementGuid>aa433c20-2f81-4faf-97a2-7da601f0fcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Numeric question'])[1]/following::span[9]</value>
      <webElementGuid>ffba1a0f-aa3e-4b03-87dd-23d775315f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from question bank'])[4]/preceding::span[1]</value>
      <webElementGuid>2de69ec6-db9e-4c74-9f9c-ad2a1221837b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a random question'])[4]/preceding::span[2]</value>
      <webElementGuid>7c5a579b-83f8-45ef-b5c2-0a3e625dcff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/div/div/div/a/span</value>
      <webElementGuid>d5db559a-d234-4b5a-a7ba-ba609e625efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionmenuaction-13' and (text() = 'a new question' or . = 'a new question')]</value>
      <webElementGuid>edafd497-f460-4671-9ba9-d306bcf89b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
