<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Course Expiration Notification to Student</name>
   <tag></tag>
   <elementGuidId>af9988ed-c015-4367-a3b1-2f0ed85631c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1740983428685_3275</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Course Expiration Notification to Student']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8313ad9c-f3af-4c48-9ac7-aca7b24889d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>173ae117-5385-4544-9c36-d91869f04003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fheader</value>
      <webElementGuid>4bf7ab0e-44ec-4cff-9150-c27ff51cba78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8b41e51-8dfb-4373-bd8a-31a4ba956e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>id_configheadernotify_student_before_course_expiration</value>
      <webElementGuid>a9e26437-52a0-4747-a169-3cacd864e85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e61a2984-a795-4616-9e6c-8c5bba0b5e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1740983428685_3275</value>
      <webElementGuid>6fb508cb-607d-4a1d-8833-121e792cc6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Course Expiration Notification to Student</value>
      <webElementGuid>d8f109ac-7318-4c87-b900-c8710beaa5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1740983428685_3275&quot;)</value>
      <webElementGuid>cb789bd5-803e-41d4-ac31-ac50dd127f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1740983428685_3275']</value>
      <webElementGuid>4c66bcd6-0f9e-4851-9555-3abad6dfb762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//legend[@id='yui_3_17_2_1_1740983428685_3276']/a</value>
      <webElementGuid>23b36bcf-3e66-4cc9-acc1-12308c001087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Course Expiration Notification to Student')]</value>
      <webElementGuid>965b0956-2b50-4227-abf4-2f2ec3d1af6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{course_link}'])[2]/following::a[1]</value>
      <webElementGuid>db85f0e1-6717-45e5-94f7-b6e0636156de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{course_fullname}'])[3]/following::a[1]</value>
      <webElementGuid>7dfce532-2e73-45c0-bd69-94ce12409191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enabled'])[7]/preceding::a[1]</value>
      <webElementGuid>9d7fbd4a-3d1a-4881-86a6-3604e71ef378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Days Before Course Expires'])[1]/preceding::a[1]</value>
      <webElementGuid>734f1e6a-608b-4ee0-84e4-4c6b102a3f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Course Expiration Notification to Student']/parent::*</value>
      <webElementGuid>8f80c27c-d733-4a4b-a566-c1d6222a0c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[14]</value>
      <webElementGuid>04ebfabc-3f5a-43d5-8ddb-62cfcfdf0372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[8]/legend/a</value>
      <webElementGuid>484e4da1-1344-4121-b20c-435037e77577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'yui_3_17_2_1_1740983428685_3275' and (text() = 'Course Expiration Notification to Student' or . = 'Course Expiration Notification to Student')]</value>
      <webElementGuid>d8c2ecbc-bcfb-4d74-8f28-c61e09523dc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
