<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_course_link_enabled_notify_student_be_9a924e</name>
   <tag></tag>
   <elementGuidId>d45e98fa-0109-42a5-87cd-fd36722ff295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_enabled_notify_student_before_course_expiration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_enabled_notify_student_before_course_expiration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63918f8a-ff80-44ab-a35a-5e88e57e110e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6 </value>
      <webElementGuid>4012ea64-e9a5-40cd-b864-08efce55791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7fa2c9ad-f9e4-4b77-9f26-b3f5bd1225df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_enabled_notify_student_before_course_expiration</value>
      <webElementGuid>ef05e63e-636d-4b63-be76-3fa93155f042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enabled_notify_student_before_course_expiration</value>
      <webElementGuid>b88a10a6-31ae-4616-bf88-bcc07d5e424b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_enabled_notify_student_before_course_expiration&quot;)</value>
      <webElementGuid>5b0774ab-7011-44d7-9578-d9a6fcc6d2ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_enabled_notify_student_before_course_expiration']</value>
      <webElementGuid>782da63e-2a80-4e3d-b867-3dbf6ca9dc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1740983428685_3287']/input</value>
      <webElementGuid>4653a04f-d4a9-4b46-9304-3481f3055f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[8]/div/div/input</value>
      <webElementGuid>4355d1cd-6366-4a88-abc1-2039d9842633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'id_enabled_notify_student_before_course_expiration' and @name = 'enabled_notify_student_before_course_expiration']</value>
      <webElementGuid>6e1a0e8b-6274-4d65-8a42-341141b543d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
