<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_link_enabled_notify_on_course_incomplete</name>
   <tag></tag>
   <elementGuidId>bd632efb-7cfd-4a00-a6a8-8413bf9b1721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_enabled_notify_on_course_incomplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_enabled_notify_on_course_incomplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>903503d3-598f-4265-a138-192389f1a239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6 </value>
      <webElementGuid>6087999f-8631-437b-b267-fd266d2832c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b22acd2e-4b40-455c-80a2-73b3e82a2e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_enabled_notify_on_course_incomplete</value>
      <webElementGuid>1ef52250-18ce-4ac7-8a0a-6b1132c7e531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enabled_notify_on_course_incomplete</value>
      <webElementGuid>9cbcd22d-67f2-4455-a5a7-24e9f159fd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_enabled_notify_on_course_incomplete&quot;)</value>
      <webElementGuid>3d56f35a-5f0e-4f5b-a873-66ea2070d20d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_enabled_notify_on_course_incomplete']</value>
      <webElementGuid>16a3b930-4dff-48ae-adf2-460a12e94b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1740983428685_3258']/input</value>
      <webElementGuid>c10b2bc3-edfa-488a-a507-9f2a91754d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div/div/input</value>
      <webElementGuid>95a39a07-46f2-4dce-95f9-259583abb139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'id_enabled_notify_on_course_incomplete' and @name = 'enabled_notify_on_course_incomplete']</value>
      <webElementGuid>80c9ca92-3ded-413a-bd9b-c257b969765d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
