<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Multi Tenant_left-footer</name>
   <tag></tag>
   <elementGuidId>8ad6dbee-eb17-49b6-ab80-9711b8997f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.left-footer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Tenant'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Custom Navigation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7b0c7996-44cb-43ab-8d65-59ac5edf9c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c0927cba-15e3-4918-b5da-c01e43ac0f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left-footer</value>
      <webElementGuid>39483e64-65cb-4294-a271-ed644e984809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24.001</value>
      <webElementGuid>9c57a305-2663-412d-844e-ff9c75882a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>23.5</value>
      <webElementGuid>8689160f-302e-405f-aaf6-be43690c2b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24.001 23.5</value>
      <webElementGuid>9c448590-f490-4edc-831e-6c17194c5692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-drawer&quot;)/div[@class=&quot;wrapper w-two&quot;]/div[@class=&quot;helpdesk&quot;]/div[@class=&quot;help_button&quot;]/a[@class=&quot;help_desk_button customnav&quot;]/span[1]/svg[@class=&quot;left-footer&quot;]</value>
      <webElementGuid>64a42e58-5ef7-406e-97f0-e242d3b1d06e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Tenant'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>917b4b5b-289d-45a0-9249-c24654826dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi tenant'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>9e347aec-8f31-466e-a38b-38c97d4b140c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Retention Summary'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>facd7ff2-4aac-4c72-ba5e-34700f0d3d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get the mobile app'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>d0135048-4847-429c-a578-08f5d011dc26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
