<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_potentialusers_clearbutton</name>
   <tag></tag>
   <elementGuidId>64cb0097-a804-4849-ac8b-b64c6a59859f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='potentialusers_clearbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#potentialusers_clearbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b07882a2-867e-4788-a8d0-d6961341f5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daf710ae-ad42-498b-8c78-2760e4ae4dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>51b686b0-b49e-4643-a542-d2531e58008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary mx-1</value>
      <webElementGuid>822d3e4e-d1dd-4a53-909e-db57bcb88074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>potentialusers_clearbutton</value>
      <webElementGuid>7ca510ff-8c8b-4ccd-a487-fc82794e0d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;potentialusers_clearbutton&quot;)</value>
      <webElementGuid>a1624046-39db-4062-9ce2-b1339f139b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='potentialusers_clearbutton']</value>
      <webElementGuid>3a0f2b24-c686-491d-9b92-233a70bd98d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741853265403_85']/input[2]</value>
      <webElementGuid>e07c195a-c0b2-4641-9237-84a40fffdc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/input[2]</value>
      <webElementGuid>b67b3cb9-5fc6-4760-a9d0-67f311f77397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'potentialusers_clearbutton']</value>
      <webElementGuid>58355351-2007-48f1-80b5-e0eb7863f396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
