<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_potentialcourses_searchtext</name>
   <tag></tag>
   <elementGuidId>699e3f1a-551c-4ff0-9424-23f603032eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='potentialcourses_searchtext']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#potentialcourses_searchtext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>273526ae-52e2-43ec-854f-79c312ac58c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af9112f0-f312-4aad-ac61-f578e163c5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a70d7c7d-0d5e-4ca4-a7e2-fb24b9cdb5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potentialcourses_searchtext</value>
      <webElementGuid>5efea3e0-a8cd-4dd6-9166-7bcfd68cf655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>potentialcourses_searchtext</value>
      <webElementGuid>77a1f9dc-843a-404c-a00a-0bc4365e4f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>9c85e964-2b4d-4d84-9340-a451cfbf48e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>205fbc6a-273c-4d9b-8059-a85b6243c519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;potentialcourses_searchtext&quot;)</value>
      <webElementGuid>549ff83a-9396-4b34-8e3e-bfe19858f115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='potentialcourses_searchtext']</value>
      <webElementGuid>1a709a93-beb1-4191-aadd-b089ee9e7f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='potentialcourses_wrapper']/div[2]/input</value>
      <webElementGuid>8556b7a4-e7bd-42c7-bd05-b4725faf2deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div[2]/input</value>
      <webElementGuid>cacb4b4d-4f15-4688-bbf1-92368bfea2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @name = 'potentialcourses_searchtext' and @id = 'potentialcourses_searchtext']</value>
      <webElementGuid>4271787e-20e1-42df-9df7-0d3ea2956851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
