<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_potentialcohorts_searchtext</name>
   <tag></tag>
   <elementGuidId>5379c5f2-549e-4218-8ab5-9cb706250676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='potentialcohorts_searchtext']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#potentialcohorts_searchtext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52436f3e-c34a-4211-b552-c8bcf76566ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42cc45e3-4fa5-4048-a4c2-e12351e0ad90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3bde22d2-f53f-4117-b402-1ea51a4fccde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potentialcohorts_searchtext</value>
      <webElementGuid>80a32f82-a58b-46b1-85d6-08b70784570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>potentialcohorts_searchtext</value>
      <webElementGuid>2adf50be-1525-416f-a90c-1c02d87e39d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>aaab7d0f-7199-4655-a6ae-1c9144a2535b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a430ff08-6642-4686-aa13-6e76cd3c761d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;potentialcohorts_searchtext&quot;)</value>
      <webElementGuid>b20b286f-2d51-400d-9736-30ea7fd1cbb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='potentialcohorts_searchtext']</value>
      <webElementGuid>99892e8e-9493-48b4-8443-7caa50a9ea78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741700520686_33']/input</value>
      <webElementGuid>f4abb380-f4f7-449f-8003-dc3195938d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div[2]/input</value>
      <webElementGuid>d41bbae9-146c-40b2-ae06-8243d411cfc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @name = 'potentialcohorts_searchtext' and @id = 'potentialcohorts_searchtext']</value>
      <webElementGuid>39f8d953-199c-4b99-91a8-00c902c16cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
