<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_potentialcourses_clearbutton</name>
   <tag></tag>
   <elementGuidId>54783ff1-055d-4358-b747-e528c42de786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='potentialcourses_clearbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#potentialcourses_clearbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81675aca-a266-46be-9d28-14c7934db8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>43393000-dadd-4ed4-a12e-1442a5378e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>0f741ce4-c398-4998-b2c0-2bf16df2d7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potentialcourses_clearbutton</value>
      <webElementGuid>78d0d7b7-dd25-46e2-9a18-3daae49e2720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>potentialcourses_clearbutton</value>
      <webElementGuid>63b101b7-9ebf-4a5b-a883-7c05dd2532cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>81d81fa4-a54a-43e7-86dd-ec4191157fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>91a3f007-8c2a-4dba-9a1e-3b78ec049c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;potentialcourses_clearbutton&quot;)</value>
      <webElementGuid>8d08dc3e-a223-4945-aec4-ed74392f09e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='potentialcourses_clearbutton']</value>
      <webElementGuid>1a9c100c-686f-42f5-a173-6084ac1ce109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741845948382_33']/input[2]</value>
      <webElementGuid>105feceb-fdd9-4638-86c2-130db6abcc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div[2]/input[2]</value>
      <webElementGuid>cfbfbbd2-7493-43e6-ba15-a8475eefcd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @placeholder = 'Search' and @name = 'potentialcourses_clearbutton' and @id = 'potentialcourses_clearbutton']</value>
      <webElementGuid>2f7c9ea0-24af-46a5-b141-321040e16d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
