<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_hruta hruta (manashmail.com)hruta1 h_e50a15</name>
   <tag></tag>
   <elementGuidId>b3252f29-c40f-4367-b201-e7356ea5f3e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#potentialusers</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='potentialusers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4a4140c-7afa-42e2-87a5-17b14ac9e243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potentialusers[]</value>
      <webElementGuid>03595494-ce66-4a3f-b6a4-6d727f1451b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>potentialusers</value>
      <webElementGuid>dc4d2d03-7bc1-4bfa-b53f-4385773bad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>0a83424c-b605-4f3d-9b56-0b0145177fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9ccbb5cb-ddf3-4192-bcd1-78f7d54ec6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control no-overflow</value>
      <webElementGuid>54dc0bb4-f6cf-4f33-a016-c174e4685a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  
  
hruta hruta (manash@mail.com)hruta1 hruta1 (hruta1@mail.com)hruta11 hruta11 (hruta2326@mail.com)hruta1601 hruta1601 (hruta1601@mail.com)hruta1701 hruta1701 (hruta1701@mail.com)hruta2 hruta2 (hruta2@mail.com)hruta200 hruta200 (hruta200@mail.com)hruta201 hruta201 (hruta201@mail.com)hruta202 hruta202 (hruta2022@mail.com)hruta203 hruta203 (hruta203@mail.com)hruta204 hruta204 (hruta204@mail.com)hruta205 hruta205 (hruta205@mail.com)hruta3 hruta3 (hruta3@mail.com)hruta4 hruta4 (hruta4@mail.com)hruta5 hruta5 (hruta5@mail.com)hruta6 hruta6 (hruta6@mail.com)hruta7 hruta7 (hruta7@mail.com)hrutamobile hrutamobile (hrutamobile@mail.com) </value>
      <webElementGuid>fce43939-cd04-446d-afe0-1b29808688fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;potentialusers&quot;)</value>
      <webElementGuid>cdce5b0f-70cc-4e4f-a1de-00a592ed1f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='potentialusers']</value>
      <webElementGuid>23186ded-4de7-4273-b396-13dbfc2ef77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='potentialusers_wrapper']/select</value>
      <webElementGuid>6e4a6080-8038-41d9-81e9-1a158e66aed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potential users to add'])[1]/following::select[1]</value>
      <webElementGuid>fe885096-80ec-4c92-a24b-c2a40e859f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match the search text anywhere in the displayed fields'])[1]/following::select[1]</value>
      <webElementGuid>60112cf5-9276-4d93-ad15-ee1bd81c743d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::select[1]</value>
      <webElementGuid>1ee1cbe9-93fa-48df-bc7f-7d2d07de1b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Side panel'])[1]/preceding::select[1]</value>
      <webElementGuid>611db8b4-e314-4b9a-9897-3f3dfc70692b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/select</value>
      <webElementGuid>c326d341-2e25-41c7-a00c-38cc4c22e036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'potentialusers[]' and @id = 'potentialusers' and (text() = '&#xd;
  &#xd;
  &#xd;
hruta hruta (manash@mail.com)hruta1 hruta1 (hruta1@mail.com)hruta11 hruta11 (hruta2326@mail.com)hruta1601 hruta1601 (hruta1601@mail.com)hruta1701 hruta1701 (hruta1701@mail.com)hruta2 hruta2 (hruta2@mail.com)hruta200 hruta200 (hruta200@mail.com)hruta201 hruta201 (hruta201@mail.com)hruta202 hruta202 (hruta2022@mail.com)hruta203 hruta203 (hruta203@mail.com)hruta204 hruta204 (hruta204@mail.com)hruta205 hruta205 (hruta205@mail.com)hruta3 hruta3 (hruta3@mail.com)hruta4 hruta4 (hruta4@mail.com)hruta5 hruta5 (hruta5@mail.com)hruta6 hruta6 (hruta6@mail.com)hruta7 hruta7 (hruta7@mail.com)hrutamobile hrutamobile (hrutamobile@mail.com) ' or . = '&#xd;
  &#xd;
  &#xd;
hruta hruta (manash@mail.com)hruta1 hruta1 (hruta1@mail.com)hruta11 hruta11 (hruta2326@mail.com)hruta1601 hruta1601 (hruta1601@mail.com)hruta1701 hruta1701 (hruta1701@mail.com)hruta2 hruta2 (hruta2@mail.com)hruta200 hruta200 (hruta200@mail.com)hruta201 hruta201 (hruta201@mail.com)hruta202 hruta202 (hruta2022@mail.com)hruta203 hruta203 (hruta203@mail.com)hruta204 hruta204 (hruta204@mail.com)hruta205 hruta205 (hruta205@mail.com)hruta3 hruta3 (hruta3@mail.com)hruta4 hruta4 (hruta4@mail.com)hruta5 hruta5 (hruta5@mail.com)hruta6 hruta6 (hruta6@mail.com)hruta7 hruta7 (hruta7@mail.com)hrutamobile hrutamobile (hrutamobile@mail.com) ')]</value>
      <webElementGuid>9b345373-23ee-40bf-8265-a7f20497ef31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
