<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Page content of katalon workspace</name>
   <tag></tag>
   <elementGuidId>fe2082fe-e571-466f-9d3e-df167d0cb0f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee13ec45-7436-402d-adc9-8305d777e43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-3</value>
      <webElementGuid>6c5b7785-233a-4b68-aea8-3122440fa38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2e7b7800-5df7-4f4d-b833-5d404dbb9724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>5c68884f-8472-4005-92f8-d3533ea18f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Page content of katalon workspace</value>
      <webElementGuid>9a89f849-747b-4bb4-9f26-48a61f70711b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-3&quot;)</value>
      <webElementGuid>91cf91ad-e460-4aa0-b11b-a8c1c56c5131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']</value>
      <webElementGuid>ad230eda-6fbf-43c6-9f71-07961c01b1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-2']/li/div</value>
      <webElementGuid>42898baf-f68c-4251-89b4-4ba20f4414c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am Admin Assistant.'])[1]/following::div[2]</value>
      <webElementGuid>ea2cb5a8-9722-41c9-ada9-7ff9b5348b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page content of katalon workspace'])[6]/preceding::div[1]</value>
      <webElementGuid>94af7946-bb40-4867-87d6-1e7c2b422b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/div</value>
      <webElementGuid>f08cf6b5-5947-4584-b25b-0e866494ad9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-3' and (text() = 'Page content of katalon workspace' or . = 'Page content of katalon workspace')]</value>
      <webElementGuid>59d0b183-95d1-4afa-8b55-6dcb4bc8fa09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
