<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Company Workspace_fa fa-angle-down role</name>
   <tag></tag>
   <elementGuidId>81513725-257e-42e2-b09c-7dcd8968fdca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenu1']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-down.role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fec5aa60-8188-4e4b-8782-d60f46e6994a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-down role</value>
      <webElementGuid>a88f8c55-6a52-4bdf-8746-4495b0103163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d1713bd-b957-446e-a646-cc41fe0536e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenu1&quot;)/i[@class=&quot;fa fa-angle-down role&quot;]</value>
      <webElementGuid>b6862946-822f-42e7-8cbe-eb4a9ca4a283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenu1']/i</value>
      <webElementGuid>5269a06b-44ac-4e12-b31d-f8b7b3d5a2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/i</value>
      <webElementGuid>82492dbc-8e5f-4920-8185-2e9b96a13917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
