<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>d16f53f9-efde-44ee-be7d-f378dd907ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1742283953279_584</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='action-menu-4-menu']/a[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5a7c326-db52-4033-b203-57b43f7e83bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/course/mod.php?sesskey=zVN9hxO36o&amp;sr=0&amp;delete=9726</value>
      <webElementGuid>1a7ca26b-6b41-47b9-a1ee-72f516fdffb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item editing_delete menu-action</value>
      <webElementGuid>6c7de750-30ad-4a03-bb63-5375d3534efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>9815b2de-7c6d-4432-8bbc-8fc352c5fcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sectionreturn</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>40a5d9a7-2b37-4f32-8fdb-b335405a2691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4c84a50e-75ad-43a6-b1fe-79dee94c20fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>actionmenuaction-21</value>
      <webElementGuid>46eab3ee-9faa-4bbd-a5fa-9e49eb117fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1742283953279_584</value>
      <webElementGuid>30eb9fc3-dba3-4772-b631-c1eb143a06db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            Delete
    </value>
      <webElementGuid>f9630bbd-5abb-4250-8695-5d912c47d468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742283953279_584&quot;)</value>
      <webElementGuid>aa896971-d113-4d8f-9c21-3c4734b56583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1742283953279_584']</value>
      <webElementGuid>546167de-24cb-426f-ab61-bf8d3976ce35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-menu-4-menu']/a[8]</value>
      <webElementGuid>e59ffa85-ea32-45ff-9542-d98e706f5045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Roles'])[2]/following::a[1]</value>
      <webElementGuid>0f632219-ed01-44b7-9d67-db4ed40b200e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Groups (Click To Change)'])[2]/following::a[2]</value>
      <webElementGuid>49e1c7ae-34b1-445d-92f1-167f39632d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The system marks this item complete according to conditions: Katalon Quiz update'])[1]/preceding::a[1]</value>
      <webElementGuid>bb1a3eba-93cf-4f28-bfb2-3cd8e6d3e7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=zVN9hxO36o&amp;sr=0&amp;delete=9726')]</value>
      <webElementGuid>bf49bfec-2ddf-4135-ab58-dc93c2daa9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/div/div[2]/span/div/div/div/div/a[8]</value>
      <webElementGuid>739c5cb7-b8da-4e5b-9595-55312f426d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=zVN9hxO36o&amp;sr=0&amp;delete=9726' and @id = 'yui_3_17_2_1_1742283953279_584' and (text() = '
            
            Delete
    ' or . = '
            
            Delete
    ')]</value>
      <webElementGuid>1a525289-71c5-4092-b690-e6ae551feb64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
