<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1_2</name>
   <tag></tag>
   <elementGuidId>9e0542f8-4291-49b1-9d59-36799f3d6ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_feedback_0editable > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_answer_1editable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>97333d22-2940-4faa-a66d-0d999ca3a6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>061e5c33-642e-46ad-b715-7c3c17940c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_feedback_0editable&quot;)/p[1]</value>
      <webElementGuid>968bba61-68fa-4928-bba6-28b578279a5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_feedback_0editable']/p</value>
      <webElementGuid>baf08b8f-67db-4f2f-811f-1a47b0cfed57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::p[1]</value>
      <webElementGuid>21c92cbb-6b69-4bfe-8be7-48b7cd02bb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/following::p[1]</value>
      <webElementGuid>2ada7e21-e8e6-401d-a1ca-3013d484c915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choice 2'])[1]/preceding::p[1]</value>
      <webElementGuid>48a698c9-c4c0-47c1-be44-5c42a5977fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[2]/preceding::p[2]</value>
      <webElementGuid>5f60aedf-687c-41c9-92db-c418240b24ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[3]/div[2]/div/div/div/div[2]/div/p</value>
      <webElementGuid>c5aca409-7222-4dd2-a31f-6e9287ceaf44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
