<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Catalog</name>
   <tag></tag>
   <elementGuidId>f9db1ba6-fb63-4e9e-aa63-1265cd4eb9fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='itemid_61']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.menu-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8839cca4-e0f7-4b3b-92d4-b9bfb5930b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>c5f92318-d0f0-4e5e-a518-bce3bc9a0574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Catalog </value>
      <webElementGuid>ef0ae0be-796c-4371-a0a2-a5c44aef6201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Catalog</value>
      <webElementGuid>bb539b8c-e3a9-47f6-ac57-e8951bc543aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_lefnavigation&quot;)/ul[@id=&quot;subitem61&quot;]/li[@id=&quot;itemid_61&quot;]/a[@class=&quot;dropdown-item&quot;]/span[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>5ac77f38-f1f4-415b-a197-c767e9d2e870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='itemid_61']/a/span</value>
      <webElementGuid>29f1fa54-e1b4-4a66-b707-84490c10e90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Achievements'])[1]/following::span[2]</value>
      <webElementGuid>ea63213c-c22a-4fab-948f-b7097019c18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Profile'])[1]/following::span[2]</value>
      <webElementGuid>9d9b97b9-c1a4-48de-ad5b-05aca2eef32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a Category'])[1]/preceding::span[1]</value>
      <webElementGuid>d8ecf89c-1bb4-40c7-92f4-bb1d906d73f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a Course'])[1]/preceding::span[2]</value>
      <webElementGuid>9714a23b-2866-4e30-bb31-169d738b329b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Catalog']/parent::*</value>
      <webElementGuid>4e435f80-12f2-4888-b64a-bfbc0b428530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/span</value>
      <webElementGuid>6e33650d-222b-448c-ae88-429f4f3d10c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = ' Catalog ' and (text() = 'Catalog' or . = 'Catalog')]</value>
      <webElementGuid>184e4054-3d21-4bae-af69-a08ade56e811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
