<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EnableEnable</name>
   <tag></tag>
   <elementGuidId>69d4f15d-49e7-4a8e-8387-6abf4dc0d5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enable_rule-627</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Enable Enable&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8f70fdb-2b09-45d8-af1e-ff00e693ead3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>17eaf9ce-8179-4f95-9e98-d7b6c9104761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ruleid</name>
      <type>Main</type>
      <value>627</value>
      <webElementGuid>86bee4b8-8f63-4026-be2d-e409bcfb6f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enable_rule dropdown-item 111</value>
      <webElementGuid>985dd5e4-bd0c-4281-9275-362c99cc1003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enable_rule-627</value>
      <webElementGuid>523f3955-8cde-4915-a59d-3a1d1e78af0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Enable</value>
      <webElementGuid>db4eb69b-79ce-40d5-b66f-9401c2e5cf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enable</value>
      <webElementGuid>bf60fc73-521a-46d8-bd11-8fe95a125d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EnableEnable</value>
      <webElementGuid>6cd92e5d-64d7-41a9-8f00-c4a467d677d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enable_rule-627&quot;)</value>
      <webElementGuid>e1313bb6-d629-4639-9141-388b53f3f7f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='enable_rule-627']</value>
      <webElementGuid>b0564622-0504-4945-b034-d4ccc5b1376f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1737541016373_20']/div/a[3]</value>
      <webElementGuid>c2e36c84-310b-42a5-9d99-47f891bae8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/following::a[1]</value>
      <webElementGuid>d9229aca-e4a0-46c3-8073-b590983cbfcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::a[1]</value>
      <webElementGuid>5e612561-f294-4ee9-a1eb-84a60112a625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>7f04aa15-a17f-4478-b205-adcee18bf615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/div/a[3]</value>
      <webElementGuid>81fe9544-b21c-4b97-b178-73d5e48731cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'enable_rule-627' and @alt = 'Enable' and @title = 'Enable' and (text() = 'EnableEnable' or . = 'EnableEnable')]</value>
      <webElementGuid>108e34c8-8da5-4391-9b5a-1a2e83fccc72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
