<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Value_textmatch1</name>
   <tag></tag>
   <elementGuidId>a06b71f0-2949-4407-a040-43d3447e5917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_content1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_content1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Value\n\t\n\tUse Role Shortname As Value&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e10ce8a8-132f-4f2d-8bfc-5f2dfb7a03ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a97c7261-109c-4be6-92ee-10e2a25b6be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textmatch1</value>
      <webElementGuid>d0411a32-ee12-4322-8353-5963dc1b3b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_content1</value>
      <webElementGuid>0a26f565-1ed6-4c82-86fc-fbfd259e02eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control content-value</value>
      <webElementGuid>39e35752-ce26-4537-8753-394756dc4943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_content1&quot;)</value>
      <webElementGuid>25f7ef88-ae9e-4acb-8742-263ff0962cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_content1']</value>
      <webElementGuid>e695e6a4-f219-4693-a314-c71dfba96b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_input_element1']/label/div/input</value>
      <webElementGuid>a4c174af-2d7c-480b-a2c2-fe26c833aedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/div/input</value>
      <webElementGuid>a52d5f15-02b6-49c3-8f19-79221c25b6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'textmatch1' and @id = 'id_content1']</value>
      <webElementGuid>09acd5c1-e508-4640-99bd-ccbd4e4477cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
