<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Completed_completionstatusallscos</name>
   <tag></tag>
   <elementGuidId>8d9f9623-f523-43f4-b290-e021e60b2164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_completionstatusallscos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_completionstatusallscos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e502924e-ba1f-4128-846b-f306b0c3daf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f2fba41-e0da-4f52-8b2f-2a471a17632d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>completionstatusallscos</value>
      <webElementGuid>4240622e-a79d-4187-a4ab-f4c572636b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>69fd4c7c-e311-4fcb-a45a-f002482a8ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_completionstatusallscos</value>
      <webElementGuid>a133134a-bfca-4774-9395-4f3839859470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_completionstatusallscos&quot;)</value>
      <webElementGuid>887dcf71-5b1f-40fb-8ec8-6378baf421f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_completionstatusallscos']</value>
      <webElementGuid>f66b8711-cb05-4d17-9e72-73901b1d0a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741259650398_1439']/input</value>
      <webElementGuid>17589fd3-2172-4441-9c65-64a9de33a7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/input</value>
      <webElementGuid>16751f1b-6e37-4597-881c-703c2de43282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'completionstatusallscos' and @id = 'id_completionstatusallscos']</value>
      <webElementGuid>ceeef861-c418-43b8-ba64-da44f30aea88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
