<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Course completion_mustbecompleted</name>
   <tag></tag>
   <elementGuidId>e44264aa-c008-4a16-ae41-6e2f8dba6305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_mustbecompleted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_mustbecompleted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5181943-58ac-4ea7-9883-3d5d9ed08ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fbf54276-59ae-414e-b07b-40cf2c7cb3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mustbecompleted</value>
      <webElementGuid>92e87404-4c45-480b-ad6e-23f1f8fd24f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>09961038-0c35-45e6-8560-5d1a682f49df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_mustbecompleted</value>
      <webElementGuid>52d427b6-053c-4b9a-9f3f-50779abad97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_mustbecompleted&quot;)</value>
      <webElementGuid>00c9bf75-2365-414c-aa93-0feae1f2e241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_mustbecompleted']</value>
      <webElementGuid>55205afb-46e8-4f92-838b-9698b311a6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741259650398_2200']/input</value>
      <webElementGuid>7fef4272-f2c9-42d8-87ae-55b155c4dffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[10]/div/div[3]/div[2]/input</value>
      <webElementGuid>f8bf62d3-0016-4a05-9b72-29f3f10604f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'mustbecompleted' and @id = 'id_mustbecompleted']</value>
      <webElementGuid>3ef17983-86f7-49c0-92be-9598fb559973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
