<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Paradiso Solutions_yui_3_17_2_1_174290964_34c3de</name>
   <tag></tag>
   <elementGuidId>61d9d9a5-048e-44ca-8890-51d41ea010ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1742909647708_166</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='yui_3_17_2_1_1742909647708_166']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ac4e01ec-247b-4b9d-a535-760a081bb826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-trash fa-fw </value>
      <webElementGuid>e7133856-b948-4659-b8ff-570abbefeb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>dcaf2ee2-8efd-4447-9b14-2aa69c1b26f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>e9c988d3-43aa-4e7e-adfa-069d0efdbd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1742909647708_166</value>
      <webElementGuid>effc5334-b129-4a87-9018-88b73e56f9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1742909647708_166&quot;)</value>
      <webElementGuid>783f2717-a5d3-4ae3-b067-6c240889c405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='yui_3_17_2_1_1742909647708_166']</value>
      <webElementGuid>ba100b8d-3ed0-45ce-9779-959e1463bfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='action_link67e2b10600a4620']/i</value>
      <webElementGuid>f5fefe8c-780a-406c-ac8b-d6d56c87c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a[2]/i</value>
      <webElementGuid>8445435a-3620-4e7f-ba06-42aca0544a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Delete' and @id = 'yui_3_17_2_1_1742909647708_166']</value>
      <webElementGuid>b5a5dc60-8a9d-4ed0-932a-db80c69676d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
