<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_id</name>
   <tag></tag>
   <elementGuidId>cfbeca34-7167-47a5-b024-c64c8914cc5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkboxc25d25def2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-bulk-actions']/div/table/tbody/tr/td/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;id\[\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5667e670-bb05-48b3-a36f-34454ca965ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24579</value>
      <webElementGuid>ce140d32-fb64-4be1-adc7-f73030094396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8e2d9739-7f22-4c27-ad87-285ba84cb266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxc25d25def2</value>
      <webElementGuid>089e22a3-eb41-43ee-bbd4-113dee1ee29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id[]</value>
      <webElementGuid>5c1a3c25-0e3a-4af4-b90d-53a385bce451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxc25d25def2&quot;)</value>
      <webElementGuid>9ccbafcd-f241-44ba-8d73-c44d8c6315d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkboxc25d25def2']</value>
      <webElementGuid>2c302b6f-efb1-4fb4-b333-10961eee834a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-bulk-actions']/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>7a03b2f0-f0e4-4ad9-963d-a7589e2d64b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>e342ec6a-6d11-462b-bff4-001c60f9e145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkboxc25d25def2' and @name = 'id[]']</value>
      <webElementGuid>4d28ea6c-5746-4b3e-82d6-5c47a8b2e398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
