<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(ja)_keepmeloggedin</name>
   <tag></tag>
   <elementGuidId>27f18fdb-b6ea-4bd6-908e-73d38789168a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keepmeloggedin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keepmeloggedin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d538467-1a5d-4694-adf6-171cea5ff2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dc900aaa-8856-4818-9482-d9c389ed5e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keepmeloggedin</value>
      <webElementGuid>d117eeb9-955d-4ca7-bd10-f647a1b3eb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keepmeloggedin</value>
      <webElementGuid>2b10405c-8d0b-42ba-a134-855cdf81f30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ce7e0be9-7871-4376-8212-8c2d0f6856cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keepmeloggedin&quot;)</value>
      <webElementGuid>f65c4063-4bbd-4563-9273-ad17924f5334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keepmeloggedin']</value>
      <webElementGuid>5dc430bd-af5c-4a73-b26e-b0199b4b74fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div[4]/input</value>
      <webElementGuid>358411a2-69e0-4afa-8786-b2f9ec7217f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>8c09a475-e763-485f-b0d1-9ad99dd8b847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'keepmeloggedin' and @id = 'keepmeloggedin']</value>
      <webElementGuid>d0dc1aac-7bdb-4349-b32c-339c325c5fbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
