<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cohorts</name>
   <tag></tag>
   <elementGuidId>f33f902d-a602-4d5a-b694-4efdae8438ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cohorts-button > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='cohorts-button']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3640cbee-424e-4a30-b092-babfbab25c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>11f01f78-1218-4c74-840f-d109d1249b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>f5153459-c3a3-4dc0-94b8-55fbe4f06426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#learningpath-cohorts-tab</value>
      <webElementGuid>97b8758d-83d5-4f68-9d25-fbc3714111f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cohorts</value>
      <webElementGuid>8f0a9068-e517-42d5-98ab-d74757421af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cohorts-button&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>a4815b62-6b98-43bd-a850-9df080ec0c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='cohorts-button']/a</value>
      <webElementGuid>fb8ac187-81d4-47bf-b691-95f8c417ea81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cohorts')]</value>
      <webElementGuid>0c6c94cb-3fa2-406c-9ab9-3b182d833c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[1]</value>
      <webElementGuid>dff382b7-25f5-4abd-b661-056dd62c5e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses'])[1]/following::a[2]</value>
      <webElementGuid>bfdc85cd-b21a-48f3-bfca-1263968cf944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[4]/preceding::a[1]</value>
      <webElementGuid>740a4aa9-3ba8-4f4d-a061-5d95bef0a990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Not Set)'])[1]/preceding::a[2]</value>
      <webElementGuid>f2a52ad8-84bd-466b-8ee9-076664ce83df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cohorts']/parent::*</value>
      <webElementGuid>e3599ac1-2e03-4f2b-bfaa-f90fa82580c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#learningpath-cohorts-tab')]</value>
      <webElementGuid>b8873cf6-5276-453e-b9a1-da04f300cc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/a</value>
      <webElementGuid>ca39802a-2234-4449-8316-0aef7cdbfc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#learningpath-cohorts-tab' and (text() = 'Cohorts' or . = 'Cohorts')]</value>
      <webElementGuid>3eacd04e-5215-4f1d-8f3f-30dc93648e2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
