<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delete</name>
   <tag></tag>
   <elementGuidId>5cbd6bf1-3eda-4ebc-9ac9-2440ab1948e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#learningpath-remove-cohorts > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='learningpath-remove-cohorts']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0370b9e4-9c2c-44a0-aa93-3b04767a6c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5c64bcf8-aea8-416d-a0e6-1bfd04f4fbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;learningpath-remove-cohorts&quot;)/span[1]</value>
      <webElementGuid>8ddf9d19-6439-498e-b565-f9dbea34fe4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='learningpath-remove-cohorts']/span</value>
      <webElementGuid>161711fe-18cc-4230-a77d-8ef71a9fdf4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Records Found.'])[2]/following::span[3]</value>
      <webElementGuid>e4ceafe6-821e-4776-a462-06e642f5c9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrol Users'])[1]/following::span[3]</value>
      <webElementGuid>dfed366c-89dd-48bc-80d9-84081dd5e0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Cohorts'])[1]/preceding::span[1]</value>
      <webElementGuid>f4f773e9-81ff-43a5-b2ce-448183149bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cohort Name'])[1]/preceding::span[5]</value>
      <webElementGuid>789f1147-2985-4e27-ad32-ef2862845708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>99648055-b552-4bb1-838a-f60d850465ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span/a/span</value>
      <webElementGuid>8ce72e0f-43f5-49ed-acb4-2fef59733a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>559835bc-0dac-4e61-a56c-363f656717a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
