<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit</name>
   <tag></tag>
   <elementGuidId>a94cde11-9e63-4e02-a15a-3a525b43fd85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='region-main']/div/div/div/div[3]/table/tbody/tr[3]/td[4]/span/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6711071e-4650-44a5-bcf3-fb4f502d5fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>19b7733b-b998-413f-bc1c-45e7b7241cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region-main&quot;)/div[@class=&quot;card card-block content-shadow not-card&quot;]/div[1]/div[@class=&quot;content-title&quot;]/div[@class=&quot;plms-learningpaths p-4&quot;]/table[@class=&quot;table generaltable row col-xs-12 col-sm-12 title_lp_index&quot;]/tbody[1]/tr[@class=&quot;plms-learningpath mar-btm&quot;]/td[@class=&quot;learningpaths-actions&quot;]/span[@class=&quot;action-box&quot;]/a[@class=&quot;settings-learning-path edit-learning-path&quot;]/span[2]</value>
      <webElementGuid>806fd8d0-75db-4677-8ecf-ba6eaae74d69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='region-main']/div/div/div/div[3]/table/tbody/tr[3]/td[4]/span/a/span[2]</value>
      <webElementGuid>7e2057e4-6b58-42e4-8b3c-6c5a65d984b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[5]/following::span[1]</value>
      <webElementGuid>28aff033-7cd1-4449-93d2-71538ceb4691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Not Set)'])[6]/following::span[3]</value>
      <webElementGuid>191e1a66-1a5b-4243-8b4f-0c60e75a08ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA &amp; DEB'])[1]/preceding::span[1]</value>
      <webElementGuid>f18ca66e-8d0f-4651-9643-77ff58888f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Not Set)'])[7]/preceding::span[1]</value>
      <webElementGuid>ed7a7437-7271-448b-9251-2ca71c116186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/span/a/span[2]</value>
      <webElementGuid>09239e2b-5dce-4573-8a04-33a150e268ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>4f768084-2025-4ae6-ad48-58648c9cfd64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
