<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_field_firstname</name>
   <tag></tag>
   <elementGuidId>e7340852-ff3d-48ca-8e1a-212eb0739016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_field_firstname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_field_firstname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31e48b13-a913-413d-971a-a6d944780625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>40e2d45e-dd89-4c8d-8a56-1d1a71a2d25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_firstname</value>
      <webElementGuid>31f627cf-9ba5-4812-bcf9-4660a60f510a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>f4751bb6-a27e-44d3-91b8-88bd4896ebb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_field_firstname</value>
      <webElementGuid>7a4eac54-ca3e-484d-b354-9260f1d0f584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>a7784372-fb48-4e40-8a8f-0ec8c1b20f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_field_firstname&quot;)</value>
      <webElementGuid>216290b8-b03f-47fd-9e4d-730c518d546d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_field_firstname']</value>
      <webElementGuid>54f49a47-2485-4f1f-8fb3-9f4948f4c97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='yui_3_17_2_1_1743682936125_1151']/input[2]</value>
      <webElementGuid>c0ef9928-0580-447d-98ee-4c615d95aac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input[2]</value>
      <webElementGuid>f705edd6-ffb5-4d44-b306-44040dd63f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'field_firstname' and @id = 'id_field_firstname']</value>
      <webElementGuid>9540b7e1-3553-49da-84ae-b5325d5f5f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
