<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Match the search text anywhere in the_89f7b5</name>
   <tag></tag>
   <elementGuidId>9f822890-3adb-4b20-b436-3c43756731fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>218a57a3-14a6-41b4-bac9-2beeb75d1b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>c48a353f-1e88-4da2-ab7c-6b4054821aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>655a459c-1642-4ae1-ab18-89a3a0ceb9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f5896b55-7380-46a6-99ae-7a20fd103a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>◄ Add</value>
      <webElementGuid>c5a438cd-6161-4b12-ac2b-612c357e1c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>fe15c890-46cf-4af5-a45f-dde8578dcc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add&quot;)</value>
      <webElementGuid>89aea327-417f-4b23-a8ac-a9fb306f8310</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add']</value>
      <webElementGuid>80920c6f-876b-4422-8e39-16e71ff2073d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addcontrols']/input</value>
      <webElementGuid>3d5b77fb-d785-495f-8ac5-871598370ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>bb51d8c5-ecb8-4b13-af52-d2fcb60ab2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'add' and @id = 'add' and @type = 'submit' and @title = 'Add']</value>
      <webElementGuid>088e465e-c036-4f72-adf8-6d7d8392b330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
