<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Sample SCORM 1 - Complete  Incomplete_1a00d0</name>
   <tag></tag>
   <elementGuidId>01992f89-12b2-46f5-8a1d-7ae60da5f1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniqueDomId-1560</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//image[@id = 'uniqueDomId-1560']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>851d94d8-f02c-4f9e-b8ff-d8d03b9ea559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>scale(1, 1)</value>
      <webElementGuid>afabfa3c-32c0-4dac-aa37-8445217c9ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniqueDomId-1560</value>
      <webElementGuid>fd34c89b-c67f-424f-be6f-0189425e9f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>01</value>
      <webElementGuid>407983c8-6c04-4167-8bd1-de7d6ec5f72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e6bcbfb5-c5f0-486b-b575-85efbd2d8e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e351316c-2363-439c-9a9f-f32952c850b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>262804ad-fb3f-4c60-bb2c-45e9be75458f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/pluginfile.php/53540/mod_scorm/content/1/mobile/5eZ7mgbMu9X_80_DX130_DY130_CX65_CY65.png</value>
      <webElementGuid>05ac6e3f-4f62-46a4-a150-db781aac127b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>e37eaba3-1257-4cc8-b5f1-83a21b237809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>12cfc375-1246-46b5-88c7-27b51f3b02a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7f4a17b6-ea90-4ee0-be9d-2dae3e02fa47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-accepts</name>
      <type>Main</type>
      <value>events</value>
      <webElementGuid>82aad274-18c0-4d14-94c5-3ca65a9cf9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.5.4.0.1.0:$_player=163DDkbgYYTK=16ekEWzDHn6r.0.3:$c601.1:$c678.$slideobject1529.0:$4.$slideobject1557.$0.$0.$1</value>
      <webElementGuid>e4316444-895f-41aa-a934-aba3c13aaabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqueDomId-1560&quot;)</value>
      <webElementGuid>4eb3c157-b48f-4660-86b1-c083a731f538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SCROM_Activity_in_Course/Page_Katalon_Activity Test creation course Scrom/iframe_Sample SCORM 1 - Complete  Incomplet_d080b2</value>
      <webElementGuid>ba061250-de85-40a7-88e4-ff2afb66f837</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//image[@id = 'uniqueDomId-1560']</value>
      <webElementGuid>2f95c9b2-d4ad-47b7-9800-4a16461cf571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
