<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Sample SCORM 1 - Complete  Incomplete_acad50</name>
   <tag></tag>
   <elementGuidId>a8852cd4-6a64-42f0-8f99-38b84b719e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniqueDomId-1778</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;uniqueDomId-2298&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>279cacfd-adea-4061-83ee-e0f22efd6ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>scale(1, 1)</value>
      <webElementGuid>7a8cb8fc-95ab-4003-a1de-92afb949325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniqueDomId-1778</value>
      <webElementGuid>71cf8693-9cf5-4aa2-8605-0d6f49a98d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>01</value>
      <webElementGuid>7d2c1b62-6a01-438e-a088-3075d452dc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2d2bd9f8-3818-4b3c-b1bb-f793afcb0ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f129ad7-5c8e-402c-b480-cee222c7e4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4ce2fcfe-cb46-470a-ae08-51e1fb86625e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/pluginfile.php/53540/mod_scorm/content/1/mobile/5tCfCcnFdFo_80_DX130_DY130_CX65_CY64.png</value>
      <webElementGuid>17fa7cf6-cfd3-4c34-bb33-eabe40f7c3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>03a9a26f-4d81-4482-921c-8394e7bb15e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>369220bc-b669-4886-8d8f-a5362b8be250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8e488554-e59b-458c-9aa7-01882534970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-accepts</name>
      <type>Main</type>
      <value>events</value>
      <webElementGuid>2aebc7e9-ecfa-4aed-b057-4b06f9fee0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.5.4.0.1.0:$_player=163DDkbgYYTK=16ekEWzDHn6r.0.3:$c601.1:$c988.$slideobject1747.0:$4.$slideobject1775.$0.$0.$1</value>
      <webElementGuid>08ae0c7a-abc4-4dd3-a7c9-848224942a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqueDomId-1778&quot;)</value>
      <webElementGuid>2ddf6835-0c50-4e21-9c5e-c9ce29a1eff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SCROM_Activity_in_Course/Page_Katalon_Activity Test creation course Scrom/iframe_Sample SCORM 1 - Complete  Incomplet_d080b2</value>
      <webElementGuid>c6096e5e-73f5-4cb5-b618-7db96d9639ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//image[@id = 'uniqueDomId-1778']</value>
      <webElementGuid>7f2720c8-49d4-4818-ab01-0ca93c2e5eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
