<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Sample SCORM 1 - Complete  Incomplete_d8f33c</name>
   <tag></tag>
   <elementGuidId>f9ccdc4e-1db4-4da3-b329-0c86c5dab690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniqueDomId-1934</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;uniqueDomId-2552&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>b582d19b-e30b-4f00-9a74-6b4ca4804896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>scale(1, 1)</value>
      <webElementGuid>a16c8e8d-1bf5-4f20-99b5-f881565dfe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniqueDomId-1934</value>
      <webElementGuid>7ea649e9-0e1e-4d36-a4cf-7f38fcbf87ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>01</value>
      <webElementGuid>d8d1cbde-3976-47bf-b6e8-7fed80905e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1286751-eb7a-4e31-8801-1d4cefe3841d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ae8f139-82eb-41eb-8b6c-d8ec23373eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>343e89e1-016f-4772-80d3-1f4b7b56e564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/pluginfile.php/53540/mod_scorm/content/1/mobile/6pmk5lo91BE_80_DX130_DY130_CX64_CY65.png</value>
      <webElementGuid>9bc4c6b2-77a5-480b-a339-0a0aa7a54899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>1daab9c5-6cfb-4bff-9712-8d7a4035c77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>c84df868-4684-42a8-8a05-41924d42501a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>317bfec0-45dd-4675-ad07-1c9256477303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-accepts</name>
      <type>Main</type>
      <value>events</value>
      <webElementGuid>59544cdd-2689-441d-ae89-987448d1a3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.5.4.0.1.0:$_player=163DDkbgYYTK=16ekEWzDHn6r.0.3:$c601.1:$c1222.$slideobject1903.0:$4.$slideobject1931.$0.$0.$1</value>
      <webElementGuid>f0b9f1a6-101f-401d-80fc-8a7d6e893278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqueDomId-1934&quot;)</value>
      <webElementGuid>64473bfc-3b9c-459d-a40e-26feab0ad87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SCROM_Activity_in_Course/Page_Katalon_Activity Test creation course Scrom/iframe_Sample SCORM 1 - Complete  Incomplet_d080b2</value>
      <webElementGuid>a49bea8c-057f-40dd-99ba-7c92111acbd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//image[@id = 'uniqueDomId-1934']</value>
      <webElementGuid>981a75ff-57df-4893-898a-69619f1b3c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
