<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Sample SCORM 1 - Complete  Incomplete_15277d</name>
   <tag></tag>
   <elementGuidId>ce5f5e74-0bdd-4bc1-aa7b-1c1bfa830dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniqueDomId-1729</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//image[@id = 'uniqueDomId-1729']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1b6a2702-b88b-49e7-a42a-f71798b11f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>scale(1, 1)</value>
      <webElementGuid>0d99cd89-78b7-436e-b973-89aea7f174c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniqueDomId-1729</value>
      <webElementGuid>bbe0136f-4f0a-4c8b-98d1-0fefe4ddcea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>01</value>
      <webElementGuid>640bdc56-c854-4dc1-a444-1e274383373e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6ba0578-d79a-4edd-945d-441839e352f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0de9b967-15bd-44b0-b3ab-5a6dfa882de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>725f54ac-56ff-4bf0-ae24-211e4cdf3566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/pluginfile.php/53540/mod_scorm/content/1/mobile/5zy4XMMQod9_80_DX130_DY130_CX65_CY65.png</value>
      <webElementGuid>106eb6b8-c5a4-48d5-aad6-eb9970a0a896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>5e0b4fc1-6369-4bef-afbb-c273861c3bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>a5232eae-b115-45fe-9b16-4658f792fbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8f2a73be-f187-4cfe-bac5-949d7464856e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-accepts</name>
      <type>Main</type>
      <value>events</value>
      <webElementGuid>45de943c-4cd3-4c50-ac6a-4efaa31c0375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.5.4.0.1.0:$_player=163DDkbgYYTK=16ekEWzDHn6r.0.3:$c601.1:$c928.$slideobject1698.0:$4.$slideobject1726.$0.$0.$1</value>
      <webElementGuid>4f79a090-54ec-45fe-93c5-879ad5558821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqueDomId-1729&quot;)</value>
      <webElementGuid>fe1616ce-b16f-4a7f-92e5-828f5ad92614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SCROM_Activity_in_Course/Page_Katalon_Activity Test creation course Scrom/iframe_Sample SCORM 1 - Complete  Incomplet_d080b2</value>
      <webElementGuid>842baa99-38f0-4d8f-8ef0-38e908988ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//image[@id = 'uniqueDomId-1729']</value>
      <webElementGuid>f8f89bc0-329f-48b6-8a4c-e9cf74ff5239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
