<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Sample SCORM 1 - Complete  Incomplete_uniqueDomId-380</name>
   <tag></tag>
   <elementGuidId>2684b219-f197-4278-8450-9be061aed590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniqueDomId-380</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;uniqueDomId-378&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>d9d7ae42-d5ce-4fab-a289-fb122fe65184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M0,0L187,0 187,85 0,85z</value>
      <webElementGuid>59f64b4b-5888-463e-9c25-db09b1d86d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniqueDomId-380</value>
      <webElementGuid>5515b844-99d7-43a0-960f-1a8e539d934a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#05445C</value>
      <webElementGuid>4a638a44-3285-426e-8497-871687259906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0f9c61da-83ae-4fa8-a042-3166fd714eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>31645f5a-a774-443a-a5c9-7a3e5a5946c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#05445C</value>
      <webElementGuid>a8f87a15-50a5-40d3-8bd8-b544883a9927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e6751696-9fd2-4c87-8d0a-615c8f6f6699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>flat</value>
      <webElementGuid>20453211-6f58-4e15-b5a7-a716ec6c68e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fef81939-cad2-412c-839d-c51485bb75d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stroke-sharpened</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e62bbdd-be5a-4456-8b91-c519cf0db8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(0.5, 0.5)</value>
      <webElementGuid>f8b68353-aaf1-4638-bea7-a5c77aec7510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-accepts</name>
      <type>Main</type>
      <value>events</value>
      <webElementGuid>6d0b58c1-6d3b-4e5c-9b85-d8b51b4da65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.5.4.0.1.0:$_player=163DDkbgYYTK=16ncYFdDY7Jf.0.3:$c280.1:$c295.$slideobject375.$0.$0.$1.$0.$0</value>
      <webElementGuid>5b9e765e-6c92-498b-9c1b-b9879d4ee2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqueDomId-380&quot;)</value>
      <webElementGuid>84aa8498-e90f-42fe-b945-9ca22b2006d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SCROM_Activity_in_Course/Page_Katalon_Activity Test creation course Scrom/iframe_Sample SCORM 1 - Complete  Incomplet_d080b2</value>
      <webElementGuid>1a23e044-b56f-401c-814a-4bab6592009c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//path[@id = 'uniqueDomId-380']</value>
      <webElementGuid>751f1402-a6cd-4fc8-863e-f200c36d281b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
