<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_duedateenabled</name>
   <tag></tag>
   <elementGuidId>fd8010c8-8e48-4c0e-a66b-fe10c5c6f46c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_duedate_enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_duedate_enabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>554d7e02-b372-43b6-9831-bc254b3c4cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>61f51808-7204-45da-ae6a-5144acc33e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>duedate[enabled]</value>
      <webElementGuid>abb6f520-cd49-44cd-9eca-eddf93e72e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input form-group</value>
      <webElementGuid>719a4313-e8fe-4edd-9d1d-eec281638880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_duedate_enabled</value>
      <webElementGuid>95f65439-3f4b-42c9-bee7-09cda065a18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ade3e0ae-21a4-4a5f-a94c-9727378e26dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_duedate_enabled&quot;)</value>
      <webElementGuid>11dc59bb-36f7-4a90-a12e-fbd881dba491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_duedate_enabled']</value>
      <webElementGuid>45c26a50-dbe5-46b3-aac5-3f3f058d7470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='yui_3_17_2_1_1742367231203_1797']/input</value>
      <webElementGuid>4131bd65-d7ad-442e-9317-197f1fb8cf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/fieldset/div/label/input</value>
      <webElementGuid>3e8b2edd-6730-4e2e-869b-46c6a9f97b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'duedate[enabled]' and @id = 'id_duedate_enabled']</value>
      <webElementGuid>ccce3c05-1567-4a2b-bba3-a2d09bf10e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
