<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grade</name>
   <tag></tag>
   <elementGuidId>5d7c4f0c-9e82-4b14-8973-c45c9a0d1393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='linkmaincontent']/div[2]/div[2]/center/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.submissionlinks > a.btn.btn-primary.btn-round</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d7f5f43-95a0-414e-a783-5bb3871f593c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/mod/assign/view.php?id=9731&amp;action=grader</value>
      <webElementGuid>fbcb253f-3584-42ea-9f99-77045c164296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-round</value>
      <webElementGuid>9ea6735a-3ac3-4082-ad95-9a1b5ac9cf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grade</value>
      <webElementGuid>2fb395e6-7870-4dd4-9244-ecd2080d01b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkmaincontent&quot;)/div[2]/div[@class=&quot;gradingsummary&quot;]/center[1]/div[@class=&quot;submissionlinks&quot;]/a[@class=&quot;btn btn-primary btn-round&quot;]</value>
      <webElementGuid>912048e2-963a-4c3a-bb4d-a25487dac2cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkmaincontent']/div[2]/div[2]/center/div/a[2]</value>
      <webElementGuid>a3812143-0dcf-4209-a0bd-707c353ee2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Grade')])[2]</value>
      <webElementGuid>94d4aed0-5971-4a23-9ce8-47cdb6f33c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all submissions'])[2]/following::a[1]</value>
      <webElementGuid>70682ece-80b0-48a4-956d-6fb0f9bd4fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Needs grading'])[1]/following::a[2]</value>
      <webElementGuid>d44002e5-cd1c-4a0e-9134-27a8ffa88a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission status'])[1]/preceding::a[1]</value>
      <webElementGuid>ad0bffcd-2dd7-4701-96eb-fd0c6c3fd2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission status'])[2]/preceding::a[1]</value>
      <webElementGuid>d78538d8-30e0-4edd-8308-d9c446cac654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grade']/parent::*</value>
      <webElementGuid>993cef1b-0766-4f08-9709-14211ea8d8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/mod/assign/view.php?id=9731&amp;action=grader')]</value>
      <webElementGuid>0b172b9d-d5c0-4f0f-9c3d-fc6f08fb5add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/div/a[2]</value>
      <webElementGuid>c157b2cd-d22d-47c7-a484-6cb984aca731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/mod/assign/view.php?id=9731&amp;action=grader' and (text() = 'Grade' or . = 'Grade')]</value>
      <webElementGuid>3b7d57c9-3727-46ee-9fdf-7e4823730063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
