<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Preview_coursecontrols</name>
   <tag></tag>
   <elementGuidId>7f882a22-3f7e-4a3c-a451-917467203165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coursecontrols</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coursecontrols']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f16cfdc4-052e-4772-85bf-71e6b84afe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coursecontrols</value>
      <webElementGuid>49839498-e80a-4546-9b4f-092dad8bbe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coursecontrols&quot;)</value>
      <webElementGuid>ad74b33a-804a-45e7-a3ae-9fd7319e762a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='coursecontrols']</value>
      <webElementGuid>dbc211c9-2ac7-4c7e-abab-4f1468463f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='navbar-paradiso']/div/div[2]/div[4]/div</value>
      <webElementGuid>f7e7ccbd-1241-42dc-b40f-f0feaf443ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::div[2]</value>
      <webElementGuid>b71967e8-36b9-429e-af37-02b1dc227f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::div[10]</value>
      <webElementGuid>2446c778-eac3-4a51-8ab8-85afd82cf47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topic outline'])[1]/preceding::div[4]</value>
      <webElementGuid>3e31b6d1-1c75-43d2-a9c8-109ad17073ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon_Activity Test creation course'])[1]/preceding::div[4]</value>
      <webElementGuid>ec6ad3c1-53ab-42a7-b562-2606fa2b3d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>9f3a94c5-e4e4-402f-966a-53cc81432ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'coursecontrols']</value>
      <webElementGuid>2df4c8c8-46e8-43df-bc98-8b375fa2eeb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
