<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Katalon Page inbound and outbound Activity_1</name>
   <tag></tag>
   <elementGuidId>164fde9a-cf6e-4583-a884-55157b0405e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_autocomplete_suggestions-1743756771202-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='form_autocomplete_suggestions-1743756771202-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>70ac42cc-6465-4c60-92f4-bf4c2985c0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9b57bf11-5daa-4926-a989-467e12d0cfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>9959</value>
      <webElementGuid>d6fcf664-65a1-4e45-ba34-a763aa976249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c29727a-1f9c-4edc-a71d-8c4acf33f1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0d9ca29-457e-4b15-8317-15ffc0270c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_autocomplete_suggestions-1743756771202-0</value>
      <webElementGuid>07755845-2739-428e-bf1f-8d96bf95f135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Page inbound and outbound Activity</value>
      <webElementGuid>5afd5442-78ce-4496-a3dc-d2a77e03d53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_autocomplete_suggestions-1743756771202-0&quot;)</value>
      <webElementGuid>1f6c1d54-75a3-4a1d-b301-246ad3541ac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='form_autocomplete_suggestions-1743756771202-0']</value>
      <webElementGuid>39064d59-039e-4cef-9c97-f9c31084e465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='form_autocomplete_suggestions-1743756771202']/li</value>
      <webElementGuid>a408e459-6a4f-46cb-b3f3-214ec4668e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Selection'])[1]/following::li[1]</value>
      <webElementGuid>4d98a1c5-a353-4f96-b4f6-491af08c3f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity List:'])[1]/following::li[1]</value>
      <webElementGuid>46427bc0-7220-4de0-9953-3e2778844631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Vimeo video Activity'])[3]/preceding::li[1]</value>
      <webElementGuid>34324d53-2b70-4c89-bb53-e372f19b32e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question type'])[1]/preceding::li[2]</value>
      <webElementGuid>acb3447b-17e3-4349-bf7c-a37d37785e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>c5d20731-9527-4511-8ad3-ac76d9327c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'form_autocomplete_suggestions-1743756771202-0' and (text() = 'Katalon Page inbound and outbound Activity' or . = 'Katalon Page inbound and outbound Activity')]</value>
      <webElementGuid>647cffd1-e9b0-48a6-890f-636fabf5ec18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
