<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Katalon Vimeo video Activity_1_2</name>
   <tag></tag>
   <elementGuidId>0ff3ff94-6953-49ea-a207-979b1a6ba3da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_autocomplete_suggestions-1743756832939-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='form_autocomplete_suggestions-1743756832939-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>78261d9c-5f6c-41c2-b1e5-023bd3d68af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9a8c6604-69c0-4611-88f7-14f0291f88b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>9960</value>
      <webElementGuid>7ea256d4-5460-4e8c-adf9-ddeaddd1246b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cca00dc6-f361-424b-b382-1b12a394e5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9eec28c7-dd91-4b46-b58e-d620183f33e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_autocomplete_suggestions-1743756832939-0</value>
      <webElementGuid>e2b8d909-b130-43f3-bbc0-923f84b73287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Vimeo video Activity</value>
      <webElementGuid>5088694a-7c6f-40bc-8735-8f50eb982099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_autocomplete_suggestions-1743756832939-0&quot;)</value>
      <webElementGuid>61166083-7ba3-4b74-9a8a-846011902595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='form_autocomplete_suggestions-1743756832939-0']</value>
      <webElementGuid>85536eea-5131-46f2-82f9-f714731ccf3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='form_autocomplete_suggestions-1743756832939']/li</value>
      <webElementGuid>df46bfdc-6c45-44ad-ab90-b3efcc9ba4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity List:'])[1]/following::li[1]</value>
      <webElementGuid>4d68cea3-4648-4fe4-b322-a1f374d1406b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question type'])[1]/preceding::li[1]</value>
      <webElementGuid>cb55067a-dbd7-4179-bb4d-888b0fc9cc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of questions to generate'])[1]/preceding::li[1]</value>
      <webElementGuid>df63b849-2f65-469e-9ec0-37db8063eb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>6bc38e39-8115-430f-a976-ded19f24b5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'form_autocomplete_suggestions-1743756832939-0' and (text() = 'Katalon Vimeo video Activity' or . = 'Katalon Vimeo video Activity')]</value>
      <webElementGuid>f0a2a768-3622-4925-a2d3-56b5874167b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
