<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_There are too many results, enter a m_66b687</name>
   <tag></tag>
   <elementGuidId>4b12eacb-758f-44f1-bf82-f9c6c9ac75c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='catsearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;catsearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0671222-0936-4997-afcd-7599f5c16da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b82ce160-088e-43ba-b1a7-60db978bc3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catsearch</value>
      <webElementGuid>dce0a6ab-998d-4472-a66b-82f92bb9776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dbee130b-9831-4c84-bded-b79151ba64f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkmaincontent&quot;)/div[1]/div[@class=&quot;backup-course-selector backup-restore&quot;]/form[@class=&quot;mform&quot;]/div[@class=&quot;bcs-new-course backup-section&quot;]/div[@class=&quot;detail-pair&quot;]/div[@class=&quot;detail-pair-value pl-2&quot;]/div[@class=&quot;restore-course-search form-inline mb-1&quot;]/div[@class=&quot;rcs-search&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5349badc-6f8b-4ce5-8792-fc6f208d34a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='catsearch']</value>
      <webElementGuid>49a7894b-6f98-4b33-a5d8-c386dcc148ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkmaincontent']/div/div[2]/form/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a8b8e98a-3549-43aa-abd1-d9d4dd1574fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>14b26a20-164c-4e13-951c-950093817eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'catsearch']</value>
      <webElementGuid>d2ebf3ab-b3d0-47c0-83d0-cf69f65dc629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
