<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_None            100            90   _353130</name>
   <tag></tag>
   <elementGuidId>89668898-67ea-4e6a-b072-1b6a00051c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_fraction_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_fraction_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f92c597-512c-4f5d-9828-fbe4f1fb0d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a8a5dc80-ca71-4002-bfb6-c9fe64130044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraction[0]</value>
      <webElementGuid>3ed7c4cf-89be-4969-879d-5cf7170ea9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_fraction_0</value>
      <webElementGuid>4cafb825-f16c-467a-93ab-de43f3660aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            None
            100%
            90%
            83.33333%
            80%
            75%
            70%
            66.66667%
            60%
            50%
            40%
            33.33333%
            30%
            25%
            20%
            16.66667%
            14.28571%
            12.5%
            11.11111%
            10%
            5%
        </value>
      <webElementGuid>e46c6ffb-75a5-40a9-9f18-55e7f4484857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_fraction_0&quot;)</value>
      <webElementGuid>c33a2e6e-ab97-4666-92ea-d372ef6ceafa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_fraction_0']</value>
      <webElementGuid>360c53cd-b45b-44d1-b4ee-9445a45a14fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1743138269945_3129']/select</value>
      <webElementGuid>0d51478b-20b8-4450-a073-e6e0ea6ee5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/following::select[1]</value>
      <webElementGuid>f8be36d4-0bcb-4f46-b59c-6f048e0279f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer 1'])[3]/following::select[1]</value>
      <webElementGuid>bd9d4ce3-9664-4a73-a77f-42945a03d235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::select[1]</value>
      <webElementGuid>4d635e58-e2e7-4498-9f50-f8cab7e49a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer 2'])[1]/preceding::select[1]</value>
      <webElementGuid>d29c961d-5279-42d8-be84-169194dd5b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>3a597309-9220-4300-a267-703c9d51dc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fraction[0]' and @id = 'id_fraction_0' and (text() = '
            None
            100%
            90%
            83.33333%
            80%
            75%
            70%
            66.66667%
            60%
            50%
            40%
            33.33333%
            30%
            25%
            20%
            16.66667%
            14.28571%
            12.5%
            11.11111%
            10%
            5%
        ' or . = '
            None
            100%
            90%
            83.33333%
            80%
            75%
            70%
            66.66667%
            60%
            50%
            40%
            33.33333%
            30%
            25%
            20%
            16.66667%
            14.28571%
            12.5%
            11.11111%
            10%
            5%
        ')]</value>
      <webElementGuid>f863f5bb-93fe-4e85-aecd-90cdf2da497c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
