<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>20cb4ef4-4ec6-455d-898e-d4fd6ccd920b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reports-columns-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reports-columns-add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>859506e4-f2cc-4318-a5c6-72a881237599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reports-columns-add</value>
      <webElementGuid>f3c4958f-1135-4328-8fa0-802b6aa2f382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round btn-primary new-btn-rnd btn-report-editp</value>
      <webElementGuid>063f523e-7926-4d0e-a0e5-584d5ff82e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add </value>
      <webElementGuid>42ece1a2-41a7-49bf-a7e4-4c6a07dafe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reports-columns-add&quot;)</value>
      <webElementGuid>f46e179b-5734-4b18-bbff-8b3af82f5f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reports-columns-add']</value>
      <webElementGuid>d5f57a7f-6b00-4302-bf38-e189de24cf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741270954840_63']/button</value>
      <webElementGuid>4c87bafc-738f-4e9e-9e3d-7ed6085403d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[[help_learningpath_required_courses]]'])[1]/following::button[1]</value>
      <webElementGuid>d25ef843-263f-44a2-98ca-5c5b22e63c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[[help_learningpath_total_cohorts]]'])[1]/following::button[1]</value>
      <webElementGuid>e816b159-f43c-4ece-af1d-4aa19fdb854b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>ca784639-d958-4dc8-97e0-7d14beb30c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Columns currently in the report'])[2]/preceding::button[2]</value>
      <webElementGuid>d0f33d58-f318-4c48-b642-fb9726a1b1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>d138d374-840e-4a39-9b33-f5abdfc3442e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/button</value>
      <webElementGuid>fd87abaf-8d0c-4620-a92c-39d31da61f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reports-columns-add' and (text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>b90bc283-bfd3-467c-afd4-62b961eafad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
