<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Testing of_1</name>
   <tag></tag>
   <elementGuidId>eacfabf6-df41-49a2-b8ba-bd55f49952e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1743676975449_799</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='yui_3_17_2_1_1743676975449_799']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>69c50b42-c385-4682-8cfc-f3d2f05b3e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>a9e42ee4-831b-48d5-a137-9a7a1e6d96e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1743676975449_799</value>
      <webElementGuid>93f8714f-ed91-4d01-b302-7f67446dfd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing of</value>
      <webElementGuid>ea2837cb-1a13-4089-9e55-2644475debbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1743676975449_799&quot;)</value>
      <webElementGuid>68d3400f-f385-4557-9ad0-e6a28ff31868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='yui_3_17_2_1_1743676975449_799']</value>
      <webElementGuid>157a677f-1c29-402e-a2bf-e03f211505c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_contenteditable']/p</value>
      <webElementGuid>03fda4e2-994b-4eeb-a5bf-2d1c11beb384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Content'])[1]/following::p[1]</value>
      <webElementGuid>20a79135-1dfb-4a80-b2fe-1ed22edc504a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::p[1]</value>
      <webElementGuid>4dd6cc1f-8c87-4891-b062-4df7459f8df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Thumbnail'])[1]/preceding::p[1]</value>
      <webElementGuid>64065a48-30b7-4622-925f-5a8bd9449e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Thumbnail'])[2]/preceding::p[1]</value>
      <webElementGuid>d7c619d7-1ca6-496d-88db-3428470111e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing of']/parent::*</value>
      <webElementGuid>75db621a-cdd2-4eae-b419-8093d0957484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/p</value>
      <webElementGuid>da894f62-ee0a-42ce-a04f-3d2f40ddf758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'yui_3_17_2_1_1743676975449_799' and (text() = 'Testing of' or . = 'Testing of')]</value>
      <webElementGuid>f7597c00-85dd-456d-995f-9d68dd31ac47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
