<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Courses</name>
   <tag></tag>
   <elementGuidId>ce937388-e635-43c7-ad5a-d33653406592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav/ul/li[4]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741071503757_19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67eb4ded-1aa9-456d-90c1-cf46456a8e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-left</value>
      <webElementGuid>4c8994a3-be6e-431f-a3f0-efc8c2f5c0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Courses</value>
      <webElementGuid>702efab2-33ba-4f16-b508-3748b959df95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741071503757_19</value>
      <webElementGuid>17eadbe0-f6e6-493d-98a5-194f5e10cc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Courses</value>
      <webElementGuid>347c316e-dec5-4db5-8dbc-0938d7d53810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741071503757_19&quot;)</value>
      <webElementGuid>3f959c96-cc4d-4a38-af81-06425e6b8a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1741071503757_19']</value>
      <webElementGuid>59f8d7f3-3de5-4a16-b5c4-14424021c5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1741071503757_20']/span</value>
      <webElementGuid>47533862-5c66-4b3f-92e5-8adfc867f3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skill Advisor'])[1]/following::span[1]</value>
      <webElementGuid>b94f9792-dbf9-4600-b699-267f20cde8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skill advisor'])[1]/following::span[2]</value>
      <webElementGuid>51555bba-a630-4153-b8ea-9dbd0684780e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses'])[2]/preceding::span[1]</value>
      <webElementGuid>a6de829e-7d68-481a-8dd7-cf9aa975ad8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[4]/a/div/span</value>
      <webElementGuid>0340dfbc-8680-4c62-af62-8f60adb18ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Courses' and @id = 'yui_3_17_2_1_1741071503757_19' and (text() = 'Courses' or . = 'Courses')]</value>
      <webElementGuid>75f41c56-beab-4cb4-a5af-41ac5d6a92d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
