<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Learning Path Image_learningpath_imagechoose</name>
   <tag></tag>
   <elementGuidId>65905fe0-7f6e-4695-a834-314be7e3ac69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filepicker-button-67c19063dfb80</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filepicker-button-67c19063dfb80']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b88deb04-e8ac-4c39-ba5c-bae404e0493b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64717c4a-c7c6-4ae9-a0c5-f287e79c3573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fp-btn-choose btn-round</value>
      <webElementGuid>e747f1df-d817-4a0d-a317-a2a72babb192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filepicker-button-67c19063dfb80</value>
      <webElementGuid>de1b8d8f-9741-4275-89ae-7bb136903834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Choose a file</value>
      <webElementGuid>7cd412a9-072a-4c83-b3dd-f5c1feccd7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>learningpath_imagechoose</value>
      <webElementGuid>d14b7bb3-3cb0-4952-8d5c-8fd21998a8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepicker-button-67c19063dfb80&quot;)</value>
      <webElementGuid>1bc9ded0-442a-4b4a-83ec-b5a2882bbd6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filepicker-button-67c19063dfb80']</value>
      <webElementGuid>366e4365-8de2-4b5c-b8ec-1d7571827ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filepicker-wrapper-67c19063dfb80']/div/input</value>
      <webElementGuid>a438285b-a160-4208-956d-e9e98193ad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>ea2d1058-e9ff-4400-a805-61124bdb3e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'filepicker-button-67c19063dfb80' and @name = 'learningpath_imagechoose']</value>
      <webElementGuid>6af56e31-0ed9-4857-9fce-a470ac91c0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
