<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Workspaces_submitbutton</name>
   <tag></tag>
   <elementGuidId>9a531ce1-327f-4180-ae21-2fe0e367229b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_submitbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_submitbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60e9b594-139a-4d02-bfd9-2958ccbd9ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>27164d3c-1a4b-496a-b6ed-7e3654e7a4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-round
                    btn-primary
                    
                    </value>
      <webElementGuid>0753e091-594b-4b19-94e6-a7b1603775a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitbutton</value>
      <webElementGuid>08cce992-4083-47ca-b811-c39012c27a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_submitbutton</value>
      <webElementGuid>33b0d541-1cd1-408e-a747-21ca5e8ac8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>e6a73301-519d-44c1-8e80-5044cddb36f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_submitbutton&quot;)</value>
      <webElementGuid>e16afddb-eaad-4424-8ebd-5cd8ca041eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_submitbutton']</value>
      <webElementGuid>e429f154-fe82-413f-b2e0-b492d42836ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yui_3_17_2_1_1743772853041_818']/input</value>
      <webElementGuid>45331607-7e86-4d22-8c6b-453e96071078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/span[2]/input</value>
      <webElementGuid>f69119ad-b9ab-4ac2-8964-6ad7ac1d8eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submitbutton' and @id = 'id_submitbutton']</value>
      <webElementGuid>84e5b7c6-c8fd-4fb2-ad6d-0e14362ecc54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
