<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Duplicate</name>
   <tag></tag>
   <elementGuidId>4b90d186-3dd4-4eda-8b20-84fb18a67ee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='action-menu-4-menu']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1741071825308_763</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9ce4323-a225-4e66-b5a7-89b1d8571654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/course/mod.php?sesskey=6z2D8X9psC&amp;sr=0&amp;duplicate=9438</value>
      <webElementGuid>6faa44e7-723f-4217-9174-63ea4287468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item editing_duplicate menu-action</value>
      <webElementGuid>91a6b2b0-7d53-4ccc-b583-32848b255848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>duplicate</value>
      <webElementGuid>e10ef8a9-930f-4852-9e4f-b7891716c292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sectionreturn</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aef3ca60-b743-433c-8679-d8d2312df340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>914162b4-c93e-497d-852d-452f6c73a08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>actionmenuaction-18</value>
      <webElementGuid>b0da00ff-5b64-4d59-a9df-2cfdaf77d47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1741071825308_763</value>
      <webElementGuid>ecb3dd2a-7928-46b3-a227-48b34de1af68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            Duplicate
    </value>
      <webElementGuid>3123de9e-9856-440d-8d97-85cabb79b342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1741071825308_763&quot;)</value>
      <webElementGuid>8ae91bd7-1a4b-431f-b13d-67bce9d5f697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1741071825308_763']</value>
      <webElementGuid>f4480982-63e3-4aeb-b246-fcd24f8f001d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-menu-4-menu']/a[5]</value>
      <webElementGuid>13ca8c60-6bf4-4a9f-a950-473ec4f65985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide'])[2]/following::a[1]</value>
      <webElementGuid>9871ae2a-c704-4b08-aa74-6fe36cd3d7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Left'])[2]/following::a[2]</value>
      <webElementGuid>54ed3758-f41a-4b9b-82c6-5e5182fd2e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Roles'])[2]/preceding::a[1]</value>
      <webElementGuid>5b7f39fa-e760-455b-a083-aa098cc1fab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=6z2D8X9psC&amp;sr=0&amp;duplicate=9438')]</value>
      <webElementGuid>17e998da-295d-402f-a87b-c4ad8297635f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/div/div[2]/span/div/div/div/div/a[5]</value>
      <webElementGuid>b2413e77-d013-423e-96dd-c575630da583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://plms-php81.paradisolms.net/course/mod.php?sesskey=6z2D8X9psC&amp;sr=0&amp;duplicate=9438' and @id = 'yui_3_17_2_1_1741071825308_763' and (text() = '
            
            Duplicate
    ' or . = '
            
            Duplicate
    ')]</value>
      <webElementGuid>9d092bdc-909d-4a7b-8c90-26ecc8b3546a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
