<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Awarded by Manager_dropdownMenuButton</name>
   <tag></tag>
   <elementGuidId>7e962c6a-e703-420a-869d-14bd7ab31ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[contains(@class, 'fa-ellipsis-v')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.actions.cell.c4.lastcol > #dropdownMenuButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b6efa26b-1e05-488b-bd8b-f7358b3ba2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-v</value>
      <webElementGuid>80124538-8e00-42f7-b757-a9538dfbaac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1bd860cb-c2c9-44a6-a306-b38a31928196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton</value>
      <webElementGuid>3d78ad99-cf5c-414b-9e74-d5ab75c18787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>9db12065-ebab-4469-bf38-b412156d46bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>449cde0a-5aad-481e-8855-e5be03f859a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkmaincontent&quot;)/div[1]/table[@class=&quot;table table-bordered table-striped&quot;]/tbody[1]/tr[@class=&quot;lastrow&quot;]/td[@class=&quot;actions cell c4 lastcol&quot;]/i[@id=&quot;dropdownMenuButton&quot;]</value>
      <webElementGuid>4eda9b90-2135-429c-9954-9bfd46d53405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='dropdownMenuButton']</value>
      <webElementGuid>a340dd2b-0857-4248-a0c1-327a42aa9c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkmaincontent']/div/table/tbody/tr/td[5]/i</value>
      <webElementGuid>e8e8c0ba-31a3-4c01-8d9e-ead4c6fb1765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/i</value>
      <webElementGuid>0f346ad8-f1d0-48ca-9014-a791e687d1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@type = 'button' and @id = 'dropdownMenuButton']</value>
      <webElementGuid>013c80c6-e9ad-4007-9191-c9f0d8fcbadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
