<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Disable accessAward badgeEditCopyDelete</name>
   <tag></tag>
   <elementGuidId>a9cbc6db-e491-49d9-8f0f-7ded98239846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.actions.cell.c4.lastcol</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='linkmaincontent']/div/table/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a5739977-0005-4c31-abad-4e53fa0d8920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actions cell c4 lastcol</value>
      <webElementGuid>cdb40060-0ecd-4fdb-a1d6-c4ec1387accb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disable accessAward badgeEditCopyDelete</value>
      <webElementGuid>fb9edc8a-7080-4041-9a1c-3e49126cc7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkmaincontent&quot;)/div[1]/table[@class=&quot;table table-bordered table-striped&quot;]/tbody[1]/tr[@class=&quot;lastrow&quot;]/td[@class=&quot;actions cell c4 lastcol&quot;]</value>
      <webElementGuid>1b9dba1a-75a4-46b2-9ea7-be57f668bc35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkmaincontent']/div/table/tbody/tr/td[5]</value>
      <webElementGuid>d7e90db1-eef9-4a14-bbb8-0ea94df69d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awarded by: Manager'])[1]/following::td[2]</value>
      <webElementGuid>199eb8ab-9983-4d7b-be73-874f1d997498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available to users'])[1]/following::td[3]</value>
      <webElementGuid>a82e6ce9-6625-4d7a-a7e5-64bb21e300e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>4bb49820-4fb4-4f5f-bbf8-e4bd6c94dbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Disable accessAward badgeEditCopyDelete' or . = 'Disable accessAward badgeEditCopyDelete')]</value>
      <webElementGuid>3d30ed7e-e634-4321-b19d-b8e299aba4b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
