<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_plms 880</name>
   <tag></tag>
   <elementGuidId>48d8d784-92ce-4aa2-9fd4-4fa027100978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.click_add_users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseTwo']/div/div/div/label/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e87d362-7159-4c95-a528-c364eab2f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click_add_users</value>
      <webElementGuid>fb37f20b-d0a4-4582-ac83-c72f912c1970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-userpic</name>
      <type>Main</type>
      <value>https://plms-php81.paradisolms.net/theme/image.php/paradiso/core/1742189249/u/f1</value>
      <webElementGuid>04c8dc3c-7684-4c82-944f-f685ca9bb082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-usernm</name>
      <type>Main</type>
      <value>plms 880</value>
      <webElementGuid>5e836fdf-90cb-4887-8c4c-a37cf4457fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-userid</name>
      <type>Main</type>
      <value>12111</value>
      <webElementGuid>886971ba-7da4-4739-98b8-b9646bbc8d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>plms 880</value>
      <webElementGuid>2d48e7e3-bc0a-4c8b-aade-e3bec4ec2896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseTwo&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;search-user-result&quot;]/div[@class=&quot;item&quot;]/label[@class=&quot;container-chobx&quot;]/a[@class=&quot;click_add_users&quot;]</value>
      <webElementGuid>09f7fe59-e69e-40ec-9bc5-eead5bb301c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/div/div/label/a</value>
      <webElementGuid>fa921640-3f40-46ee-be9d-86d0fa2727db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'plms 880')]</value>
      <webElementGuid>02c34bd5-5723-4c06-bc2d-a700db01a720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[2]/following::a[1]</value>
      <webElementGuid>fa88cb1a-6f24-40c1-8703-7678347121fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cohorts'])[2]/following::a[1]</value>
      <webElementGuid>5ff6c037-1522-4fde-8827-0ca6e837bd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>f7d31796-55f1-4ec4-a495-a35108fd1485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/preceding::a[1]</value>
      <webElementGuid>f70d8b93-84ea-4b0c-8c37-09455538c6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='plms 880']/parent::*</value>
      <webElementGuid>f1d47e49-c334-4830-a5a3-8ae13d33afbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>abc7eaa2-250b-4cd0-b40b-2abb1313bc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'plms 880' or . = 'plms 880')]</value>
      <webElementGuid>8695acf3-65cb-46ad-aab1-183b8dcd8779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
